
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:03 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ARB_sparse_texture__
#define __GLUX_GL_ARB_sparse_texture__

GLUX_NEW_PLUGIN(GL_ARB_sparse_texture)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_TEXTURE_SPARSE_ARB
#    define GL_TEXTURE_SPARSE_ARB 0x91A6
#  endif
#  ifndef GL_VIRTUAL_PAGE_SIZE_INDEX_ARB
#    define GL_VIRTUAL_PAGE_SIZE_INDEX_ARB 0x91A7
#  endif
#  ifndef GL_NUM_SPARSE_LEVELS_ARB
#    define GL_NUM_SPARSE_LEVELS_ARB 0x91AA
#  endif
#  ifndef GL_NUM_VIRTUAL_PAGE_SIZES_ARB
#    define GL_NUM_VIRTUAL_PAGE_SIZES_ARB 0x91A8
#  endif
#  ifndef GL_VIRTUAL_PAGE_SIZE_X_ARB
#    define GL_VIRTUAL_PAGE_SIZE_X_ARB 0x9195
#  endif
#  ifndef GL_VIRTUAL_PAGE_SIZE_Y_ARB
#    define GL_VIRTUAL_PAGE_SIZE_Y_ARB 0x9196
#  endif
#  ifndef GL_VIRTUAL_PAGE_SIZE_Z_ARB
#    define GL_VIRTUAL_PAGE_SIZE_Z_ARB 0x9197
#  endif
#  ifndef GL_MAX_SPARSE_TEXTURE_SIZE_ARB
#    define GL_MAX_SPARSE_TEXTURE_SIZE_ARB 0x9198
#  endif
#  ifndef GL_MAX_SPARSE_3D_TEXTURE_SIZE_ARB
#    define GL_MAX_SPARSE_3D_TEXTURE_SIZE_ARB 0x9199
#  endif
#  ifndef GL_MAX_SPARSE_ARRAY_TEXTURE_LAYERS_ARB
#    define GL_MAX_SPARSE_ARRAY_TEXTURE_LAYERS_ARB 0x919A
#  endif
#  ifndef GL_SPARSE_TEXTURE_FULL_ARRAY_CUBE_MIPMAPS_ARB
#    define GL_SPARSE_TEXTURE_FULL_ARRAY_CUBE_MIPMAPS_ARB 0x91A9
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexPageCommitmentARB
typedef void (APIENTRYP PFNGLUXTEXPAGECOMMITMENTARBPROC) (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLboolean commit);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexPageCommitmentARB
extern PFNGLUXTEXPAGECOMMITMENTARBPROC glTexPageCommitmentARB;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
