
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:03 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ARB_compute_variable_group_size__
#define __GLUX_GL_ARB_compute_variable_group_size__

GLUX_NEW_PLUGIN(GL_ARB_compute_variable_group_size)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_MAX_COMPUTE_VARIABLE_GROUP_INVOCATIONS_ARB
#    define GL_MAX_COMPUTE_VARIABLE_GROUP_INVOCATIONS_ARB 0x9344
#  endif
#  ifndef GL_MAX_COMPUTE_FIXED_GROUP_INVOCATIONS_ARB
#    define GL_MAX_COMPUTE_FIXED_GROUP_INVOCATIONS_ARB 0x90EB
#  endif
#  ifndef GL_MAX_COMPUTE_VARIABLE_GROUP_SIZE_ARB
#    define GL_MAX_COMPUTE_VARIABLE_GROUP_SIZE_ARB 0x9345
#  endif
#  ifndef GL_MAX_COMPUTE_FIXED_GROUP_SIZE_ARB
#    define GL_MAX_COMPUTE_FIXED_GROUP_SIZE_ARB 0x91BF
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glDispatchComputeGroupSizeARB
typedef void (APIENTRYP PFNGLUXDISPATCHCOMPUTEGROUPSIZEARBPROC) (GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z, GLuint group_size_x, GLuint group_size_y, GLuint group_size_z);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glDispatchComputeGroupSizeARB
extern PFNGLUXDISPATCHCOMPUTEGROUPSIZEARBPROC glDispatchComputeGroupSizeARB;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
