
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ARB_texture_float__
#define __GLUX_GL_ARB_texture_float__

GLUX_NEW_PLUGIN(GL_ARB_texture_float)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_TEXTURE_RED_TYPE_ARB
#    define GL_TEXTURE_RED_TYPE_ARB 0x8C10
#  endif
#  ifndef GL_TEXTURE_GREEN_TYPE_ARB
#    define GL_TEXTURE_GREEN_TYPE_ARB 0x8C11
#  endif
#  ifndef GL_TEXTURE_BLUE_TYPE_ARB
#    define GL_TEXTURE_BLUE_TYPE_ARB 0x8C12
#  endif
#  ifndef GL_TEXTURE_ALPHA_TYPE_ARB
#    define GL_TEXTURE_ALPHA_TYPE_ARB 0x8C13
#  endif
#  ifndef GL_TEXTURE_LUMINANCE_TYPE_ARB
#    define GL_TEXTURE_LUMINANCE_TYPE_ARB 0x8C14
#  endif
#  ifndef GL_TEXTURE_INTENSITY_TYPE_ARB
#    define GL_TEXTURE_INTENSITY_TYPE_ARB 0x8C15
#  endif
#  ifndef GL_TEXTURE_DEPTH_TYPE_ARB
#    define GL_TEXTURE_DEPTH_TYPE_ARB 0x8C16
#  endif
#  ifndef GL_UNSIGNED_NORMALIZED_ARB
#    define GL_UNSIGNED_NORMALIZED_ARB 0x8C17
#  endif
#  ifndef GL_RGBA32F_ARB
#    define GL_RGBA32F_ARB 0x8814
#  endif
#  ifndef GL_RGB32F_ARB
#    define GL_RGB32F_ARB 0x8815
#  endif
#  ifndef GL_ALPHA32F_ARB
#    define GL_ALPHA32F_ARB 0x8816
#  endif
#  ifndef GL_INTENSITY32F_ARB
#    define GL_INTENSITY32F_ARB 0x8817
#  endif
#  ifndef GL_LUMINANCE32F_ARB
#    define GL_LUMINANCE32F_ARB 0x8818
#  endif
#  ifndef GL_LUMINANCE_ALPHA32F_ARB
#    define GL_LUMINANCE_ALPHA32F_ARB 0x8819
#  endif
#  ifndef GL_RGBA16F_ARB
#    define GL_RGBA16F_ARB 0x881A
#  endif
#  ifndef GL_RGB16F_ARB
#    define GL_RGB16F_ARB 0x881B
#  endif
#  ifndef GL_ALPHA16F_ARB
#    define GL_ALPHA16F_ARB 0x881C
#  endif
#  ifndef GL_INTENSITY16F_ARB
#    define GL_INTENSITY16F_ARB 0x881D
#  endif
#  ifndef GL_LUMINANCE16F_ARB
#    define GL_LUMINANCE16F_ARB 0x881E
#  endif
#  ifndef GL_LUMINANCE_ALPHA16F_ARB
#    define GL_LUMINANCE_ALPHA16F_ARB 0x881F
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
