
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_APPLE_flush_buffer_range__
#define __GLUX_GL_APPLE_flush_buffer_range__

GLUX_NEW_PLUGIN(GL_APPLE_flush_buffer_range)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_BUFFER_SERIALIZED_MODIFY_APPLE
#    define GL_BUFFER_SERIALIZED_MODIFY_APPLE 0x8A12
#  endif
#  ifndef GL_BUFFER_FLUSHING_UNMAP_APPLE
#    define GL_BUFFER_FLUSHING_UNMAP_APPLE 0x8A13
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glBufferParameteriAPPLE
typedef void (APIENTRYP PFNGLUXBUFFERPARAMETERIAPPLEPROC) (GLenum target, GLenum pname, GLint param);
#endif
#ifndef __GLUX__GLFCT_glFlushMappedBufferRangeAPPLE
typedef void (APIENTRYP PFNGLUXFLUSHMAPPEDBUFFERRANGEAPPLEPROC) (GLenum target, GLintptr offset, GLsizeiptr size);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glBufferParameteriAPPLE
extern PFNGLUXBUFFERPARAMETERIAPPLEPROC glBufferParameteriAPPLE;
#endif
#ifndef __GLUX__GLFCT_glFlushMappedBufferRangeAPPLE
extern PFNGLUXFLUSHMAPPEDBUFFERRANGEAPPLEPROC glFlushMappedBufferRangeAPPLE;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
