
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:03 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ARB_gpu_shader_int64__
#define __GLUX_GL_ARB_gpu_shader_int64__

GLUX_NEW_PLUGIN(GL_ARB_gpu_shader_int64)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_INT64_ARB
#    define GL_INT64_ARB 0x140E
#  endif
#  ifndef GL_INT64_VEC2_ARB
#    define GL_INT64_VEC2_ARB 0x8FE9
#  endif
#  ifndef GL_INT64_VEC3_ARB
#    define GL_INT64_VEC3_ARB 0x8FEA
#  endif
#  ifndef GL_INT64_VEC4_ARB
#    define GL_INT64_VEC4_ARB 0x8FEB
#  endif
#  ifndef GL_UNSIGNED_INT64_VEC2_ARB
#    define GL_UNSIGNED_INT64_VEC2_ARB 0x8FF5
#  endif
#  ifndef GL_UNSIGNED_INT64_VEC3_ARB
#    define GL_UNSIGNED_INT64_VEC3_ARB 0x8FF6
#  endif
#  ifndef GL_UNSIGNED_INT64_VEC4_ARB
#    define GL_UNSIGNED_INT64_VEC4_ARB 0x8FF7
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glUniform1i64ARB
typedef void (APIENTRYP PFNGLUXUNIFORM1I64ARBPROC) (GLint location, GLint64 x);
#endif
#ifndef __GLUX__GLFCT_glUniform2i64ARB
typedef void (APIENTRYP PFNGLUXUNIFORM2I64ARBPROC) (GLint location, GLint64 x, GLint64 y);
#endif
#ifndef __GLUX__GLFCT_glUniform3i64ARB
typedef void (APIENTRYP PFNGLUXUNIFORM3I64ARBPROC) (GLint location, GLint64 x, GLint64 y, GLint64 z);
#endif
#ifndef __GLUX__GLFCT_glUniform4i64ARB
typedef void (APIENTRYP PFNGLUXUNIFORM4I64ARBPROC) (GLint location, GLint64 x, GLint64 y, GLint64 z, GLint64 w);
#endif
#ifndef __GLUX__GLFCT_glUniform1i64vARB
typedef void (APIENTRYP PFNGLUXUNIFORM1I64VARBPROC) (GLint location, GLsizei count, const GLint64 *value);
#endif
#ifndef __GLUX__GLFCT_glUniform2i64vARB
typedef void (APIENTRYP PFNGLUXUNIFORM2I64VARBPROC) (GLint location, GLsizei count, const GLint64 *value);
#endif
#ifndef __GLUX__GLFCT_glUniform3i64vARB
typedef void (APIENTRYP PFNGLUXUNIFORM3I64VARBPROC) (GLint location, GLsizei count, const GLint64 *value);
#endif
#ifndef __GLUX__GLFCT_glUniform4i64vARB
typedef void (APIENTRYP PFNGLUXUNIFORM4I64VARBPROC) (GLint location, GLsizei count, const GLint64 *value);
#endif
#ifndef __GLUX__GLFCT_glUniform1ui64ARB
typedef void (APIENTRYP PFNGLUXUNIFORM1UI64ARBPROC) (GLint location, GLuint64 x);
#endif
#ifndef __GLUX__GLFCT_glUniform2ui64ARB
typedef void (APIENTRYP PFNGLUXUNIFORM2UI64ARBPROC) (GLint location, GLuint64 x, GLuint64 y);
#endif
#ifndef __GLUX__GLFCT_glUniform3ui64ARB
typedef void (APIENTRYP PFNGLUXUNIFORM3UI64ARBPROC) (GLint location, GLuint64 x, GLuint64 y, GLuint64 z);
#endif
#ifndef __GLUX__GLFCT_glUniform4ui64ARB
typedef void (APIENTRYP PFNGLUXUNIFORM4UI64ARBPROC) (GLint location, GLuint64 x, GLuint64 y, GLuint64 z, GLuint64 w);
#endif
#ifndef __GLUX__GLFCT_glUniform1ui64vARB
typedef void (APIENTRYP PFNGLUXUNIFORM1UI64VARBPROC) (GLint location, GLsizei count, const GLuint64 *value);
#endif
#ifndef __GLUX__GLFCT_glUniform2ui64vARB
typedef void (APIENTRYP PFNGLUXUNIFORM2UI64VARBPROC) (GLint location, GLsizei count, const GLuint64 *value);
#endif
#ifndef __GLUX__GLFCT_glUniform3ui64vARB
typedef void (APIENTRYP PFNGLUXUNIFORM3UI64VARBPROC) (GLint location, GLsizei count, const GLuint64 *value);
#endif
#ifndef __GLUX__GLFCT_glUniform4ui64vARB
typedef void (APIENTRYP PFNGLUXUNIFORM4UI64VARBPROC) (GLint location, GLsizei count, const GLuint64 *value);
#endif
#ifndef __GLUX__GLFCT_glGetUniformi64vARB
typedef void (APIENTRYP PFNGLUXGETUNIFORMI64VARBPROC) (GLuint program, GLint location, GLint64 *params);
#endif
#ifndef __GLUX__GLFCT_glGetUniformui64vARB
typedef void (APIENTRYP PFNGLUXGETUNIFORMUI64VARBPROC) (GLuint program, GLint location, GLuint64 *params);
#endif
#ifndef __GLUX__GLFCT_glGetnUniformi64vARB
typedef void (APIENTRYP PFNGLUXGETNUNIFORMI64VARBPROC) (GLuint program, GLint location, GLsizei bufSize, GLint64 *params);
#endif
#ifndef __GLUX__GLFCT_glGetnUniformui64vARB
typedef void (APIENTRYP PFNGLUXGETNUNIFORMUI64VARBPROC) (GLuint program, GLint location, GLsizei bufSize, GLuint64 *params);
#endif
#ifndef __GLUX__GLFCT_glProgramUniform1i64ARB
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORM1I64ARBPROC) (GLuint program, GLint location, GLint64 x);
#endif
#ifndef __GLUX__GLFCT_glProgramUniform2i64ARB
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORM2I64ARBPROC) (GLuint program, GLint location, GLint64 x, GLint64 y);
#endif
#ifndef __GLUX__GLFCT_glProgramUniform3i64ARB
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORM3I64ARBPROC) (GLuint program, GLint location, GLint64 x, GLint64 y, GLint64 z);
#endif
#ifndef __GLUX__GLFCT_glProgramUniform4i64ARB
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORM4I64ARBPROC) (GLuint program, GLint location, GLint64 x, GLint64 y, GLint64 z, GLint64 w);
#endif
#ifndef __GLUX__GLFCT_glProgramUniform1i64vARB
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORM1I64VARBPROC) (GLuint program, GLint location, GLsizei count, const GLint64 *value);
#endif
#ifndef __GLUX__GLFCT_glProgramUniform2i64vARB
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORM2I64VARBPROC) (GLuint program, GLint location, GLsizei count, const GLint64 *value);
#endif
#ifndef __GLUX__GLFCT_glProgramUniform3i64vARB
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORM3I64VARBPROC) (GLuint program, GLint location, GLsizei count, const GLint64 *value);
#endif
#ifndef __GLUX__GLFCT_glProgramUniform4i64vARB
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORM4I64VARBPROC) (GLuint program, GLint location, GLsizei count, const GLint64 *value);
#endif
#ifndef __GLUX__GLFCT_glProgramUniform1ui64ARB
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORM1UI64ARBPROC) (GLuint program, GLint location, GLuint64 x);
#endif
#ifndef __GLUX__GLFCT_glProgramUniform2ui64ARB
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORM2UI64ARBPROC) (GLuint program, GLint location, GLuint64 x, GLuint64 y);
#endif
#ifndef __GLUX__GLFCT_glProgramUniform3ui64ARB
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORM3UI64ARBPROC) (GLuint program, GLint location, GLuint64 x, GLuint64 y, GLuint64 z);
#endif
#ifndef __GLUX__GLFCT_glProgramUniform4ui64ARB
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORM4UI64ARBPROC) (GLuint program, GLint location, GLuint64 x, GLuint64 y, GLuint64 z, GLuint64 w);
#endif
#ifndef __GLUX__GLFCT_glProgramUniform1ui64vARB
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORM1UI64VARBPROC) (GLuint program, GLint location, GLsizei count, const GLuint64 *value);
#endif
#ifndef __GLUX__GLFCT_glProgramUniform2ui64vARB
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORM2UI64VARBPROC) (GLuint program, GLint location, GLsizei count, const GLuint64 *value);
#endif
#ifndef __GLUX__GLFCT_glProgramUniform3ui64vARB
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORM3UI64VARBPROC) (GLuint program, GLint location, GLsizei count, const GLuint64 *value);
#endif
#ifndef __GLUX__GLFCT_glProgramUniform4ui64vARB
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORM4UI64VARBPROC) (GLuint program, GLint location, GLsizei count, const GLuint64 *value);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glUniform1i64ARB
extern PFNGLUXUNIFORM1I64ARBPROC glUniform1i64ARB;
#endif
#ifndef __GLUX__GLFCT_glUniform2i64ARB
extern PFNGLUXUNIFORM2I64ARBPROC glUniform2i64ARB;
#endif
#ifndef __GLUX__GLFCT_glUniform3i64ARB
extern PFNGLUXUNIFORM3I64ARBPROC glUniform3i64ARB;
#endif
#ifndef __GLUX__GLFCT_glUniform4i64ARB
extern PFNGLUXUNIFORM4I64ARBPROC glUniform4i64ARB;
#endif
#ifndef __GLUX__GLFCT_glUniform1i64vARB
extern PFNGLUXUNIFORM1I64VARBPROC glUniform1i64vARB;
#endif
#ifndef __GLUX__GLFCT_glUniform2i64vARB
extern PFNGLUXUNIFORM2I64VARBPROC glUniform2i64vARB;
#endif
#ifndef __GLUX__GLFCT_glUniform3i64vARB
extern PFNGLUXUNIFORM3I64VARBPROC glUniform3i64vARB;
#endif
#ifndef __GLUX__GLFCT_glUniform4i64vARB
extern PFNGLUXUNIFORM4I64VARBPROC glUniform4i64vARB;
#endif
#ifndef __GLUX__GLFCT_glUniform1ui64ARB
extern PFNGLUXUNIFORM1UI64ARBPROC glUniform1ui64ARB;
#endif
#ifndef __GLUX__GLFCT_glUniform2ui64ARB
extern PFNGLUXUNIFORM2UI64ARBPROC glUniform2ui64ARB;
#endif
#ifndef __GLUX__GLFCT_glUniform3ui64ARB
extern PFNGLUXUNIFORM3UI64ARBPROC glUniform3ui64ARB;
#endif
#ifndef __GLUX__GLFCT_glUniform4ui64ARB
extern PFNGLUXUNIFORM4UI64ARBPROC glUniform4ui64ARB;
#endif
#ifndef __GLUX__GLFCT_glUniform1ui64vARB
extern PFNGLUXUNIFORM1UI64VARBPROC glUniform1ui64vARB;
#endif
#ifndef __GLUX__GLFCT_glUniform2ui64vARB
extern PFNGLUXUNIFORM2UI64VARBPROC glUniform2ui64vARB;
#endif
#ifndef __GLUX__GLFCT_glUniform3ui64vARB
extern PFNGLUXUNIFORM3UI64VARBPROC glUniform3ui64vARB;
#endif
#ifndef __GLUX__GLFCT_glUniform4ui64vARB
extern PFNGLUXUNIFORM4UI64VARBPROC glUniform4ui64vARB;
#endif
#ifndef __GLUX__GLFCT_glGetUniformi64vARB
extern PFNGLUXGETUNIFORMI64VARBPROC glGetUniformi64vARB;
#endif
#ifndef __GLUX__GLFCT_glGetUniformui64vARB
extern PFNGLUXGETUNIFORMUI64VARBPROC glGetUniformui64vARB;
#endif
#ifndef __GLUX__GLFCT_glGetnUniformi64vARB
extern PFNGLUXGETNUNIFORMI64VARBPROC glGetnUniformi64vARB;
#endif
#ifndef __GLUX__GLFCT_glGetnUniformui64vARB
extern PFNGLUXGETNUNIFORMUI64VARBPROC glGetnUniformui64vARB;
#endif
#ifndef __GLUX__GLFCT_glProgramUniform1i64ARB
extern PFNGLUXPROGRAMUNIFORM1I64ARBPROC glProgramUniform1i64ARB;
#endif
#ifndef __GLUX__GLFCT_glProgramUniform2i64ARB
extern PFNGLUXPROGRAMUNIFORM2I64ARBPROC glProgramUniform2i64ARB;
#endif
#ifndef __GLUX__GLFCT_glProgramUniform3i64ARB
extern PFNGLUXPROGRAMUNIFORM3I64ARBPROC glProgramUniform3i64ARB;
#endif
#ifndef __GLUX__GLFCT_glProgramUniform4i64ARB
extern PFNGLUXPROGRAMUNIFORM4I64ARBPROC glProgramUniform4i64ARB;
#endif
#ifndef __GLUX__GLFCT_glProgramUniform1i64vARB
extern PFNGLUXPROGRAMUNIFORM1I64VARBPROC glProgramUniform1i64vARB;
#endif
#ifndef __GLUX__GLFCT_glProgramUniform2i64vARB
extern PFNGLUXPROGRAMUNIFORM2I64VARBPROC glProgramUniform2i64vARB;
#endif
#ifndef __GLUX__GLFCT_glProgramUniform3i64vARB
extern PFNGLUXPROGRAMUNIFORM3I64VARBPROC glProgramUniform3i64vARB;
#endif
#ifndef __GLUX__GLFCT_glProgramUniform4i64vARB
extern PFNGLUXPROGRAMUNIFORM4I64VARBPROC glProgramUniform4i64vARB;
#endif
#ifndef __GLUX__GLFCT_glProgramUniform1ui64ARB
extern PFNGLUXPROGRAMUNIFORM1UI64ARBPROC glProgramUniform1ui64ARB;
#endif
#ifndef __GLUX__GLFCT_glProgramUniform2ui64ARB
extern PFNGLUXPROGRAMUNIFORM2UI64ARBPROC glProgramUniform2ui64ARB;
#endif
#ifndef __GLUX__GLFCT_glProgramUniform3ui64ARB
extern PFNGLUXPROGRAMUNIFORM3UI64ARBPROC glProgramUniform3ui64ARB;
#endif
#ifndef __GLUX__GLFCT_glProgramUniform4ui64ARB
extern PFNGLUXPROGRAMUNIFORM4UI64ARBPROC glProgramUniform4ui64ARB;
#endif
#ifndef __GLUX__GLFCT_glProgramUniform1ui64vARB
extern PFNGLUXPROGRAMUNIFORM1UI64VARBPROC glProgramUniform1ui64vARB;
#endif
#ifndef __GLUX__GLFCT_glProgramUniform2ui64vARB
extern PFNGLUXPROGRAMUNIFORM2UI64VARBPROC glProgramUniform2ui64vARB;
#endif
#ifndef __GLUX__GLFCT_glProgramUniform3ui64vARB
extern PFNGLUXPROGRAMUNIFORM3UI64VARBPROC glProgramUniform3ui64vARB;
#endif
#ifndef __GLUX__GLFCT_glProgramUniform4ui64vARB
extern PFNGLUXPROGRAMUNIFORM4UI64VARBPROC glProgramUniform4ui64vARB;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
