
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ARB_sample_locations__
#define __GLUX_GL_ARB_sample_locations__

GLUX_NEW_PLUGIN(GL_ARB_sample_locations)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_SAMPLE_LOCATION_SUBPIXEL_BITS_ARB
#    define GL_SAMPLE_LOCATION_SUBPIXEL_BITS_ARB 0x933D
#  endif
#  ifndef GL_SAMPLE_LOCATION_PIXEL_GRID_WIDTH_ARB
#    define GL_SAMPLE_LOCATION_PIXEL_GRID_WIDTH_ARB 0x933E
#  endif
#  ifndef GL_SAMPLE_LOCATION_PIXEL_GRID_HEIGHT_ARB
#    define GL_SAMPLE_LOCATION_PIXEL_GRID_HEIGHT_ARB 0x933F
#  endif
#  ifndef GL_PROGRAMMABLE_SAMPLE_LOCATION_TABLE_SIZE_ARB
#    define GL_PROGRAMMABLE_SAMPLE_LOCATION_TABLE_SIZE_ARB 0x9340
#  endif
#  ifndef GL_SAMPLE_LOCATION_ARB
#    define GL_SAMPLE_LOCATION_ARB 0x8E50
#  endif
#  ifndef GL_PROGRAMMABLE_SAMPLE_LOCATION_ARB
#    define GL_PROGRAMMABLE_SAMPLE_LOCATION_ARB 0x9341
#  endif
#  ifndef GL_FRAMEBUFFER_PROGRAMMABLE_SAMPLE_LOCATIONS_ARB
#    define GL_FRAMEBUFFER_PROGRAMMABLE_SAMPLE_LOCATIONS_ARB 0x9342
#  endif
#  ifndef GL_FRAMEBUFFER_SAMPLE_LOCATION_PIXEL_GRID_ARB
#    define GL_FRAMEBUFFER_SAMPLE_LOCATION_PIXEL_GRID_ARB 0x9343
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glFramebufferSampleLocationsfvARB
typedef void (APIENTRYP PFNGLUXFRAMEBUFFERSAMPLELOCATIONSFVARBPROC) (GLenum target, GLuint start, GLsizei count, const GLfloat *v);
#endif
#ifndef __GLUX__GLFCT_glNamedFramebufferSampleLocationsfvARB
typedef void (APIENTRYP PFNGLUXNAMEDFRAMEBUFFERSAMPLELOCATIONSFVARBPROC) (GLuint framebuffer, GLuint start, GLsizei count, const GLfloat *v);
#endif
#ifndef __GLUX__GLFCT_glEvaluateDepthValuesARB
typedef void (APIENTRYP PFNGLUXEVALUATEDEPTHVALUESARBPROC) (void);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glFramebufferSampleLocationsfvARB
extern PFNGLUXFRAMEBUFFERSAMPLELOCATIONSFVARBPROC glFramebufferSampleLocationsfvARB;
#endif
#ifndef __GLUX__GLFCT_glNamedFramebufferSampleLocationsfvARB
extern PFNGLUXNAMEDFRAMEBUFFERSAMPLELOCATIONSFVARBPROC glNamedFramebufferSampleLocationsfvARB;
#endif
#ifndef __GLUX__GLFCT_glEvaluateDepthValuesARB
extern PFNGLUXEVALUATEDEPTHVALUESARBPROC glEvaluateDepthValuesARB;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
