
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_ATI_envmap_bumpmap__
#define __GLUX_GL_ATI_envmap_bumpmap__

GLUX_NEW_PLUGIN(GL_ATI_envmap_bumpmap)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_BUMP_ROT_MATRIX_ATI
#    define GL_BUMP_ROT_MATRIX_ATI 0x8775
#  endif
#  ifndef GL_BUMP_ROT_MATRIX_SIZE_ATI
#    define GL_BUMP_ROT_MATRIX_SIZE_ATI 0x8776
#  endif
#  ifndef GL_BUMP_NUM_TEX_UNITS_ATI
#    define GL_BUMP_NUM_TEX_UNITS_ATI 0x8777
#  endif
#  ifndef GL_BUMP_TEX_UNITS_ATI
#    define GL_BUMP_TEX_UNITS_ATI 0x8778
#  endif
#  ifndef GL_DUDV_ATI
#    define GL_DUDV_ATI 0x8779
#  endif
#  ifndef GL_DU8DV8_ATI
#    define GL_DU8DV8_ATI 0x877A
#  endif
#  ifndef GL_BUMP_ENVMAP_ATI
#    define GL_BUMP_ENVMAP_ATI 0x877B
#  endif
#  ifndef GL_BUMP_TARGET_ATI
#    define GL_BUMP_TARGET_ATI 0x877C
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERIVATIPROC) (GLenum pname, const GLint *param);
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXTEXBUMPPARAMETERFVATIPROC) (GLenum pname, const GLfloat *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERIVATIPROC) (GLenum pname, GLint *param);
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
typedef void (APIENTRYP PFNGLUXGETTEXBUMPPARAMETERFVATIPROC) (GLenum pname, GLfloat *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glTexBumpParameterivATI
extern PFNGLUXTEXBUMPPARAMETERIVATIPROC glTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glTexBumpParameterfvATI
extern PFNGLUXTEXBUMPPARAMETERFVATIPROC glTexBumpParameterfvATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterivATI
extern PFNGLUXGETTEXBUMPPARAMETERIVATIPROC glGetTexBumpParameterivATI;
#endif
#ifndef __GLUX__GLFCT_glGetTexBumpParameterfvATI
extern PFNGLUXGETTEXBUMPPARAMETERFVATIPROC glGetTexBumpParameterfvATI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
