
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_EXT_cull_vertex__
#define __GLUX_GL_EXT_cull_vertex__

GLUX_NEW_PLUGIN(GL_EXT_cull_vertex)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_CULL_VERTEX_EXT
#    define GL_CULL_VERTEX_EXT 0x81AA
#  endif
#  ifndef GL_CULL_VERTEX_EYE_POSITION_EXT
#    define GL_CULL_VERTEX_EYE_POSITION_EXT 0x81AB
#  endif
#  ifndef GL_CULL_VERTEX_OBJECT_POSITION_EXT
#    define GL_CULL_VERTEX_OBJECT_POSITION_EXT 0x81AC
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glCullParameterdvEXT
typedef void (APIENTRYP PFNGLUXCULLPARAMETERDVEXTPROC) (GLenum pname, GLdouble *params);
#endif
#ifndef __GLUX__GLFCT_glCullParameterfvEXT
typedef void (APIENTRYP PFNGLUXCULLPARAMETERFVEXTPROC) (GLenum pname, GLfloat *params);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glCullParameterdvEXT
extern PFNGLUXCULLPARAMETERDVEXTPROC glCullParameterdvEXT;
#endif
#ifndef __GLUX__GLFCT_glCullParameterfvEXT
extern PFNGLUXCULLPARAMETERFVEXTPROC glCullParameterfvEXT;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
