
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_EXT_pixel_transform__
#define __GLUX_GL_EXT_pixel_transform__

GLUX_NEW_PLUGIN(GL_EXT_pixel_transform)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_PIXEL_TRANSFORM_2D_EXT
#    define GL_PIXEL_TRANSFORM_2D_EXT 0x8330
#  endif
#  ifndef GL_PIXEL_MAG_FILTER_EXT
#    define GL_PIXEL_MAG_FILTER_EXT 0x8331
#  endif
#  ifndef GL_PIXEL_MIN_FILTER_EXT
#    define GL_PIXEL_MIN_FILTER_EXT 0x8332
#  endif
#  ifndef GL_PIXEL_CUBIC_WEIGHT_EXT
#    define GL_PIXEL_CUBIC_WEIGHT_EXT 0x8333
#  endif
#  ifndef GL_CUBIC_EXT
#    define GL_CUBIC_EXT 0x8334
#  endif
#  ifndef GL_AVERAGE_EXT
#    define GL_AVERAGE_EXT 0x8335
#  endif
#  ifndef GL_PIXEL_TRANSFORM_2D_STACK_DEPTH_EXT
#    define GL_PIXEL_TRANSFORM_2D_STACK_DEPTH_EXT 0x8336
#  endif
#  ifndef GL_MAX_PIXEL_TRANSFORM_2D_STACK_DEPTH_EXT
#    define GL_MAX_PIXEL_TRANSFORM_2D_STACK_DEPTH_EXT 0x8337
#  endif
#  ifndef GL_PIXEL_TRANSFORM_2D_MATRIX_EXT
#    define GL_PIXEL_TRANSFORM_2D_MATRIX_EXT 0x8338
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glPixelTransformParameteriEXT
typedef void (APIENTRYP PFNGLUXPIXELTRANSFORMPARAMETERIEXTPROC) (GLenum target, GLenum pname, GLint param);
#endif
#ifndef __GLUX__GLFCT_glPixelTransformParameterfEXT
typedef void (APIENTRYP PFNGLUXPIXELTRANSFORMPARAMETERFEXTPROC) (GLenum target, GLenum pname, GLfloat param);
#endif
#ifndef __GLUX__GLFCT_glPixelTransformParameterivEXT
typedef void (APIENTRYP PFNGLUXPIXELTRANSFORMPARAMETERIVEXTPROC) (GLenum target, GLenum pname, const GLint *params);
#endif
#ifndef __GLUX__GLFCT_glPixelTransformParameterfvEXT
typedef void (APIENTRYP PFNGLUXPIXELTRANSFORMPARAMETERFVEXTPROC) (GLenum target, GLenum pname, const GLfloat *params);
#endif
#ifndef __GLUX__GLFCT_glGetPixelTransformParameterivEXT
typedef void (APIENTRYP PFNGLUXGETPIXELTRANSFORMPARAMETERIVEXTPROC) (GLenum target, GLenum pname, GLint *params);
#endif
#ifndef __GLUX__GLFCT_glGetPixelTransformParameterfvEXT
typedef void (APIENTRYP PFNGLUXGETPIXELTRANSFORMPARAMETERFVEXTPROC) (GLenum target, GLenum pname, GLfloat *params);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glPixelTransformParameteriEXT
extern PFNGLUXPIXELTRANSFORMPARAMETERIEXTPROC glPixelTransformParameteriEXT;
#endif
#ifndef __GLUX__GLFCT_glPixelTransformParameterfEXT
extern PFNGLUXPIXELTRANSFORMPARAMETERFEXTPROC glPixelTransformParameterfEXT;
#endif
#ifndef __GLUX__GLFCT_glPixelTransformParameterivEXT
extern PFNGLUXPIXELTRANSFORMPARAMETERIVEXTPROC glPixelTransformParameterivEXT;
#endif
#ifndef __GLUX__GLFCT_glPixelTransformParameterfvEXT
extern PFNGLUXPIXELTRANSFORMPARAMETERFVEXTPROC glPixelTransformParameterfvEXT;
#endif
#ifndef __GLUX__GLFCT_glGetPixelTransformParameterivEXT
extern PFNGLUXGETPIXELTRANSFORMPARAMETERIVEXTPROC glGetPixelTransformParameterivEXT;
#endif
#ifndef __GLUX__GLFCT_glGetPixelTransformParameterfvEXT
extern PFNGLUXGETPIXELTRANSFORMPARAMETERFVEXTPROC glGetPixelTransformParameterfvEXT;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
