
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_EXT_geometry_shader4__
#define __GLUX_GL_EXT_geometry_shader4__

GLUX_NEW_PLUGIN(GL_EXT_geometry_shader4)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_GEOMETRY_SHADER_EXT
#    define GL_GEOMETRY_SHADER_EXT 0x8DD9
#  endif
#  ifndef GL_GEOMETRY_VERTICES_OUT_EXT
#    define GL_GEOMETRY_VERTICES_OUT_EXT 0x8DDA
#  endif
#  ifndef GL_GEOMETRY_INPUT_TYPE_EXT
#    define GL_GEOMETRY_INPUT_TYPE_EXT 0x8DDB
#  endif
#  ifndef GL_GEOMETRY_OUTPUT_TYPE_EXT
#    define GL_GEOMETRY_OUTPUT_TYPE_EXT 0x8DDC
#  endif
#  ifndef GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT
#    define GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT 0x8C29
#  endif
#  ifndef GL_MAX_GEOMETRY_VARYING_COMPONENTS_EXT
#    define GL_MAX_GEOMETRY_VARYING_COMPONENTS_EXT 0x8DDD
#  endif
#  ifndef GL_MAX_VERTEX_VARYING_COMPONENTS_EXT
#    define GL_MAX_VERTEX_VARYING_COMPONENTS_EXT 0x8DDE
#  endif
#  ifndef GL_MAX_VARYING_COMPONENTS_EXT
#    define GL_MAX_VARYING_COMPONENTS_EXT 0x8B4B
#  endif
#  ifndef GL_MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT
#    define GL_MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT 0x8DDF
#  endif
#  ifndef GL_MAX_GEOMETRY_OUTPUT_VERTICES_EXT
#    define GL_MAX_GEOMETRY_OUTPUT_VERTICES_EXT 0x8DE0
#  endif
#  ifndef GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT
#    define GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT 0x8DE1
#  endif
#  ifndef GL_LINES_ADJACENCY_EXT
#    define GL_LINES_ADJACENCY_EXT 0x000A
#  endif
#  ifndef GL_LINE_STRIP_ADJACENCY_EXT
#    define GL_LINE_STRIP_ADJACENCY_EXT 0x000B
#  endif
#  ifndef GL_TRIANGLES_ADJACENCY_EXT
#    define GL_TRIANGLES_ADJACENCY_EXT 0x000C
#  endif
#  ifndef GL_TRIANGLE_STRIP_ADJACENCY_EXT
#    define GL_TRIANGLE_STRIP_ADJACENCY_EXT 0x000D
#  endif
#  ifndef GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT
#    define GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT 0x8DA8
#  endif
#  ifndef GL_FRAMEBUFFER_INCOMPLETE_LAYER_COUNT_EXT
#    define GL_FRAMEBUFFER_INCOMPLETE_LAYER_COUNT_EXT 0x8DA9
#  endif
#  ifndef GL_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT
#    define GL_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT 0x8DA7
#  endif
#  ifndef GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT
#    define GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT 0x8CD4
#  endif
#  ifndef GL_PROGRAM_POINT_SIZE_EXT
#    define GL_PROGRAM_POINT_SIZE_EXT 0x8642
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glProgramParameteriEXT
typedef void (APIENTRYP PFNGLUXPROGRAMPARAMETERIEXTPROC) (GLuint program, GLenum pname, GLint value);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glProgramParameteriEXT
extern PFNGLUXPROGRAMPARAMETERIEXTPROC glProgramParameteriEXT;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
