
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_EXT_provoking_vertex__
#define __GLUX_GL_EXT_provoking_vertex__

GLUX_NEW_PLUGIN(GL_EXT_provoking_vertex)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION_EXT
#    define GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION_EXT 0x8E4C
#  endif
#  ifndef GL_FIRST_VERTEX_CONVENTION_EXT
#    define GL_FIRST_VERTEX_CONVENTION_EXT 0x8E4D
#  endif
#  ifndef GL_LAST_VERTEX_CONVENTION_EXT
#    define GL_LAST_VERTEX_CONVENTION_EXT 0x8E4E
#  endif
#  ifndef GL_PROVOKING_VERTEX_EXT
#    define GL_PROVOKING_VERTEX_EXT 0x8E4F
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glProvokingVertexEXT
typedef void (APIENTRYP PFNGLUXPROVOKINGVERTEXEXTPROC) (GLenum mode);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glProvokingVertexEXT
extern PFNGLUXPROVOKINGVERTEXEXTPROC glProvokingVertexEXT;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
