
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:03 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_EXT_debug_marker__
#define __GLUX_GL_EXT_debug_marker__

GLUX_NEW_PLUGIN(GL_EXT_debug_marker)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glInsertEventMarkerEXT
typedef void (APIENTRYP PFNGLUXINSERTEVENTMARKEREXTPROC) (GLsizei length, const GLchar *marker);
#endif
#ifndef __GLUX__GLFCT_glPushGroupMarkerEXT
typedef void (APIENTRYP PFNGLUXPUSHGROUPMARKEREXTPROC) (GLsizei length, const GLchar *marker);
#endif
#ifndef __GLUX__GLFCT_glPopGroupMarkerEXT
typedef void (APIENTRYP PFNGLUXPOPGROUPMARKEREXTPROC) (void);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glInsertEventMarkerEXT
extern PFNGLUXINSERTEVENTMARKEREXTPROC glInsertEventMarkerEXT;
#endif
#ifndef __GLUX__GLFCT_glPushGroupMarkerEXT
extern PFNGLUXPUSHGROUPMARKEREXTPROC glPushGroupMarkerEXT;
#endif
#ifndef __GLUX__GLFCT_glPopGroupMarkerEXT
extern PFNGLUXPOPGROUPMARKEREXTPROC glPopGroupMarkerEXT;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
