
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:03 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_EXT_vertex_weighting__
#define __GLUX_GL_EXT_vertex_weighting__

GLUX_NEW_PLUGIN(GL_EXT_vertex_weighting)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_MODELVIEW0_STACK_DEPTH_EXT
#    define GL_MODELVIEW0_STACK_DEPTH_EXT 0x0BA3
#  endif
#  ifndef GL_MODELVIEW1_STACK_DEPTH_EXT
#    define GL_MODELVIEW1_STACK_DEPTH_EXT 0x8502
#  endif
#  ifndef GL_MODELVIEW0_MATRIX_EXT
#    define GL_MODELVIEW0_MATRIX_EXT 0x0BA6
#  endif
#  ifndef GL_MODELVIEW1_MATRIX_EXT
#    define GL_MODELVIEW1_MATRIX_EXT 0x8506
#  endif
#  ifndef GL_VERTEX_WEIGHTING_EXT
#    define GL_VERTEX_WEIGHTING_EXT 0x8509
#  endif
#  ifndef GL_MODELVIEW0_EXT
#    define GL_MODELVIEW0_EXT 0x1700
#  endif
#  ifndef GL_MODELVIEW1_EXT
#    define GL_MODELVIEW1_EXT 0x850A
#  endif
#  ifndef GL_CURRENT_VERTEX_WEIGHT_EXT
#    define GL_CURRENT_VERTEX_WEIGHT_EXT 0x850B
#  endif
#  ifndef GL_VERTEX_WEIGHT_ARRAY_EXT
#    define GL_VERTEX_WEIGHT_ARRAY_EXT 0x850C
#  endif
#  ifndef GL_VERTEX_WEIGHT_ARRAY_SIZE_EXT
#    define GL_VERTEX_WEIGHT_ARRAY_SIZE_EXT 0x850D
#  endif
#  ifndef GL_VERTEX_WEIGHT_ARRAY_TYPE_EXT
#    define GL_VERTEX_WEIGHT_ARRAY_TYPE_EXT 0x850E
#  endif
#  ifndef GL_VERTEX_WEIGHT_ARRAY_STRIDE_EXT
#    define GL_VERTEX_WEIGHT_ARRAY_STRIDE_EXT 0x850F
#  endif
#  ifndef GL_VERTEX_WEIGHT_ARRAY_POINTER_EXT
#    define GL_VERTEX_WEIGHT_ARRAY_POINTER_EXT 0x8510
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glVertexWeightfEXT
typedef void (APIENTRYP PFNGLUXVERTEXWEIGHTFEXTPROC) (GLfloat weight);
#endif
#ifndef __GLUX__GLFCT_glVertexWeightfvEXT
typedef void (APIENTRYP PFNGLUXVERTEXWEIGHTFVEXTPROC) (const GLfloat *weight);
#endif
#ifndef __GLUX__GLFCT_glVertexWeightPointerEXT
typedef void (APIENTRYP PFNGLUXVERTEXWEIGHTPOINTEREXTPROC) (GLint size, GLenum type, GLsizei stride, const void *pointer);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glVertexWeightfEXT
extern PFNGLUXVERTEXWEIGHTFEXTPROC glVertexWeightfEXT;
#endif
#ifndef __GLUX__GLFCT_glVertexWeightfvEXT
extern PFNGLUXVERTEXWEIGHTFVEXTPROC glVertexWeightfvEXT;
#endif
#ifndef __GLUX__GLFCT_glVertexWeightPointerEXT
extern PFNGLUXVERTEXWEIGHTPOINTEREXTPROC glVertexWeightPointerEXT;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
