
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_EXT_memory_object_win32__
#define __GLUX_GL_EXT_memory_object_win32__

GLUX_NEW_PLUGIN(GL_EXT_memory_object_win32)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_HANDLE_TYPE_OPAQUE_WIN32_EXT
#    define GL_HANDLE_TYPE_OPAQUE_WIN32_EXT 0x9587
#  endif
#  ifndef GL_HANDLE_TYPE_OPAQUE_WIN32_KMT_EXT
#    define GL_HANDLE_TYPE_OPAQUE_WIN32_KMT_EXT 0x9588
#  endif
#  ifndef GL_DEVICE_LUID_EXT
#    define GL_DEVICE_LUID_EXT 0x9599
#  endif
#  ifndef GL_DEVICE_NODE_MASK_EXT
#    define GL_DEVICE_NODE_MASK_EXT 0x959A
#  endif
#  ifndef GL_LUID_SIZE_EXT
#    define GL_LUID_SIZE_EXT 8
#  endif
#  ifndef GL_HANDLE_TYPE_D3D12_TILEPOOL_EXT
#    define GL_HANDLE_TYPE_D3D12_TILEPOOL_EXT 0x9589
#  endif
#  ifndef GL_HANDLE_TYPE_D3D12_RESOURCE_EXT
#    define GL_HANDLE_TYPE_D3D12_RESOURCE_EXT 0x958A
#  endif
#  ifndef GL_HANDLE_TYPE_D3D11_IMAGE_EXT
#    define GL_HANDLE_TYPE_D3D11_IMAGE_EXT 0x958B
#  endif
#  ifndef GL_HANDLE_TYPE_D3D11_IMAGE_KMT_EXT
#    define GL_HANDLE_TYPE_D3D11_IMAGE_KMT_EXT 0x958C
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glImportMemoryWin32HandleEXT
typedef void (APIENTRYP PFNGLUXIMPORTMEMORYWIN32HANDLEEXTPROC) (GLuint memory, GLuint64 size, GLenum handleType, void *handle);
#endif
#ifndef __GLUX__GLFCT_glImportMemoryWin32NameEXT
typedef void (APIENTRYP PFNGLUXIMPORTMEMORYWIN32NAMEEXTPROC) (GLuint memory, GLuint64 size, GLenum handleType, const void *name);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glImportMemoryWin32HandleEXT
extern PFNGLUXIMPORTMEMORYWIN32HANDLEEXTPROC glImportMemoryWin32HandleEXT;
#endif
#ifndef __GLUX__GLFCT_glImportMemoryWin32NameEXT
extern PFNGLUXIMPORTMEMORYWIN32NAMEEXTPROC glImportMemoryWin32NameEXT;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
