
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:03 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_EXT_fog_coord__
#define __GLUX_GL_EXT_fog_coord__

GLUX_NEW_PLUGIN(GL_EXT_fog_coord)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_FOG_COORDINATE_SOURCE_EXT
#    define GL_FOG_COORDINATE_SOURCE_EXT 0x8450
#  endif
#  ifndef GL_FOG_COORDINATE_EXT
#    define GL_FOG_COORDINATE_EXT 0x8451
#  endif
#  ifndef GL_FRAGMENT_DEPTH_EXT
#    define GL_FRAGMENT_DEPTH_EXT 0x8452
#  endif
#  ifndef GL_CURRENT_FOG_COORDINATE_EXT
#    define GL_CURRENT_FOG_COORDINATE_EXT 0x8453
#  endif
#  ifndef GL_FOG_COORDINATE_ARRAY_TYPE_EXT
#    define GL_FOG_COORDINATE_ARRAY_TYPE_EXT 0x8454
#  endif
#  ifndef GL_FOG_COORDINATE_ARRAY_STRIDE_EXT
#    define GL_FOG_COORDINATE_ARRAY_STRIDE_EXT 0x8455
#  endif
#  ifndef GL_FOG_COORDINATE_ARRAY_POINTER_EXT
#    define GL_FOG_COORDINATE_ARRAY_POINTER_EXT 0x8456
#  endif
#  ifndef GL_FOG_COORDINATE_ARRAY_EXT
#    define GL_FOG_COORDINATE_ARRAY_EXT 0x8457
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glFogCoordfEXT
typedef void (APIENTRYP PFNGLUXFOGCOORDFEXTPROC) (GLfloat coord);
#endif
#ifndef __GLUX__GLFCT_glFogCoordfvEXT
typedef void (APIENTRYP PFNGLUXFOGCOORDFVEXTPROC) (const GLfloat *coord);
#endif
#ifndef __GLUX__GLFCT_glFogCoorddEXT
typedef void (APIENTRYP PFNGLUXFOGCOORDDEXTPROC) (GLdouble coord);
#endif
#ifndef __GLUX__GLFCT_glFogCoorddvEXT
typedef void (APIENTRYP PFNGLUXFOGCOORDDVEXTPROC) (const GLdouble *coord);
#endif
#ifndef __GLUX__GLFCT_glFogCoordPointerEXT
typedef void (APIENTRYP PFNGLUXFOGCOORDPOINTEREXTPROC) (GLenum type, GLsizei stride, const void *pointer);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glFogCoordfEXT
extern PFNGLUXFOGCOORDFEXTPROC glFogCoordfEXT;
#endif
#ifndef __GLUX__GLFCT_glFogCoordfvEXT
extern PFNGLUXFOGCOORDFVEXTPROC glFogCoordfvEXT;
#endif
#ifndef __GLUX__GLFCT_glFogCoorddEXT
extern PFNGLUXFOGCOORDDEXTPROC glFogCoorddEXT;
#endif
#ifndef __GLUX__GLFCT_glFogCoorddvEXT
extern PFNGLUXFOGCOORDDVEXTPROC glFogCoorddvEXT;
#endif
#ifndef __GLUX__GLFCT_glFogCoordPointerEXT
extern PFNGLUXFOGCOORDPOINTEREXTPROC glFogCoordPointerEXT;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
