
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_EXT_bindable_uniform__
#define __GLUX_GL_EXT_bindable_uniform__

GLUX_NEW_PLUGIN(GL_EXT_bindable_uniform)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_MAX_VERTEX_BINDABLE_UNIFORMS_EXT
#    define GL_MAX_VERTEX_BINDABLE_UNIFORMS_EXT 0x8DE2
#  endif
#  ifndef GL_MAX_FRAGMENT_BINDABLE_UNIFORMS_EXT
#    define GL_MAX_FRAGMENT_BINDABLE_UNIFORMS_EXT 0x8DE3
#  endif
#  ifndef GL_MAX_GEOMETRY_BINDABLE_UNIFORMS_EXT
#    define GL_MAX_GEOMETRY_BINDABLE_UNIFORMS_EXT 0x8DE4
#  endif
#  ifndef GL_MAX_BINDABLE_UNIFORM_SIZE_EXT
#    define GL_MAX_BINDABLE_UNIFORM_SIZE_EXT 0x8DED
#  endif
#  ifndef GL_UNIFORM_BUFFER_EXT
#    define GL_UNIFORM_BUFFER_EXT 0x8DEE
#  endif
#  ifndef GL_UNIFORM_BUFFER_BINDING_EXT
#    define GL_UNIFORM_BUFFER_BINDING_EXT 0x8DEF
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glUniformBufferEXT
typedef void (APIENTRYP PFNGLUXUNIFORMBUFFEREXTPROC) (GLuint program, GLint location, GLuint buffer);
#endif
#ifndef __GLUX__GLFCT_glGetUniformBufferSizeEXT
typedef GLint (APIENTRYP PFNGLUXGETUNIFORMBUFFERSIZEEXTPROC) (GLuint program, GLint location);
#endif
#ifndef __GLUX__GLFCT_glGetUniformOffsetEXT
typedef GLintptr (APIENTRYP PFNGLUXGETUNIFORMOFFSETEXTPROC) (GLuint program, GLint location);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glUniformBufferEXT
extern PFNGLUXUNIFORMBUFFEREXTPROC glUniformBufferEXT;
#endif
#ifndef __GLUX__GLFCT_glGetUniformBufferSizeEXT
extern PFNGLUXGETUNIFORMBUFFERSIZEEXTPROC glGetUniformBufferSizeEXT;
#endif
#ifndef __GLUX__GLFCT_glGetUniformOffsetEXT
extern PFNGLUXGETUNIFORMOFFSETEXTPROC glGetUniformOffsetEXT;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
