
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_INTEL_map_texture__
#define __GLUX_GL_INTEL_map_texture__

GLUX_NEW_PLUGIN(GL_INTEL_map_texture)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_TEXTURE_MEMORY_LAYOUT_INTEL
#    define GL_TEXTURE_MEMORY_LAYOUT_INTEL 0x83FF
#  endif
#  ifndef GL_LAYOUT_DEFAULT_INTEL
#    define GL_LAYOUT_DEFAULT_INTEL 0
#  endif
#  ifndef GL_LAYOUT_LINEAR_INTEL
#    define GL_LAYOUT_LINEAR_INTEL 1
#  endif
#  ifndef GL_LAYOUT_LINEAR_CPU_CACHED_INTEL
#    define GL_LAYOUT_LINEAR_CPU_CACHED_INTEL 2
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glSyncTextureINTEL
typedef void (APIENTRYP PFNGLUXSYNCTEXTUREINTELPROC) (GLuint texture);
#endif
#ifndef __GLUX__GLFCT_glUnmapTexture2DINTEL
typedef void (APIENTRYP PFNGLUXUNMAPTEXTURE2DINTELPROC) (GLuint texture, GLint level);
#endif
#ifndef __GLUX__GLFCT_glMapTexture2DINTEL
typedef void *(APIENTRYP PFNGLUXMAPTEXTURE2DINTELPROC) (GLuint texture, GLint level, GLbitfield access, GLint *stride, GLenum *layout);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glSyncTextureINTEL
extern PFNGLUXSYNCTEXTUREINTELPROC glSyncTextureINTEL;
#endif
#ifndef __GLUX__GLFCT_glUnmapTexture2DINTEL
extern PFNGLUXUNMAPTEXTURE2DINTELPROC glUnmapTexture2DINTEL;
#endif
#ifndef __GLUX__GLFCT_glMapTexture2DINTEL
extern PFNGLUXMAPTEXTURE2DINTELPROC glMapTexture2DINTEL;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
