
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_draw_vulkan_image__
#define __GLUX_GL_NV_draw_vulkan_image__

GLUX_NEW_PLUGIN(GL_NV_draw_vulkan_image)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glDrawVkImageNV
typedef void (APIENTRYP PFNGLUXDRAWVKIMAGENVPROC) (GLuint64 vkImage, GLuint sampler, GLfloat x0, GLfloat y0, GLfloat x1, GLfloat y1, GLfloat z, GLfloat s0, GLfloat t0, GLfloat s1, GLfloat t1);
#endif
#ifndef __GLUX__GLFCT_glGetVkProcAddrNV
typedef GLVULKANPROCNV (APIENTRYP PFNGLUXGETVKPROCADDRNVPROC) (const GLchar *name);
#endif
#ifndef __GLUX__GLFCT_glWaitVkSemaphoreNV
typedef void (APIENTRYP PFNGLUXWAITVKSEMAPHORENVPROC) (GLuint64 vkSemaphore);
#endif
#ifndef __GLUX__GLFCT_glSignalVkSemaphoreNV
typedef void (APIENTRYP PFNGLUXSIGNALVKSEMAPHORENVPROC) (GLuint64 vkSemaphore);
#endif
#ifndef __GLUX__GLFCT_glSignalVkFenceNV
typedef void (APIENTRYP PFNGLUXSIGNALVKFENCENVPROC) (GLuint64 vkFence);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glDrawVkImageNV
extern PFNGLUXDRAWVKIMAGENVPROC glDrawVkImageNV;
#endif
#ifndef __GLUX__GLFCT_glGetVkProcAddrNV
extern PFNGLUXGETVKPROCADDRNVPROC glGetVkProcAddrNV;
#endif
#ifndef __GLUX__GLFCT_glWaitVkSemaphoreNV
extern PFNGLUXWAITVKSEMAPHORENVPROC glWaitVkSemaphoreNV;
#endif
#ifndef __GLUX__GLFCT_glSignalVkSemaphoreNV
extern PFNGLUXSIGNALVKSEMAPHORENVPROC glSignalVkSemaphoreNV;
#endif
#ifndef __GLUX__GLFCT_glSignalVkFenceNV
extern PFNGLUXSIGNALVKFENCENVPROC glSignalVkFenceNV;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
