
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_shader_buffer_load__
#define __GLUX_GL_NV_shader_buffer_load__

GLUX_NEW_PLUGIN(GL_NV_shader_buffer_load)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_BUFFER_GPU_ADDRESS_NV
#    define GL_BUFFER_GPU_ADDRESS_NV 0x8F1D
#  endif
#  ifndef GL_GPU_ADDRESS_NV
#    define GL_GPU_ADDRESS_NV 0x8F34
#  endif
#  ifndef GL_MAX_SHADER_BUFFER_ADDRESS_NV
#    define GL_MAX_SHADER_BUFFER_ADDRESS_NV 0x8F35
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glMakeBufferResidentNV
typedef void (APIENTRYP PFNGLUXMAKEBUFFERRESIDENTNVPROC) (GLenum target, GLenum access);
#endif
#ifndef __GLUX__GLFCT_glMakeBufferNonResidentNV
typedef void (APIENTRYP PFNGLUXMAKEBUFFERNONRESIDENTNVPROC) (GLenum target);
#endif
#ifndef __GLUX__GLFCT_glIsBufferResidentNV
typedef GLboolean (APIENTRYP PFNGLUXISBUFFERRESIDENTNVPROC) (GLenum target);
#endif
#ifndef __GLUX__GLFCT_glMakeNamedBufferResidentNV
typedef void (APIENTRYP PFNGLUXMAKENAMEDBUFFERRESIDENTNVPROC) (GLuint buffer, GLenum access);
#endif
#ifndef __GLUX__GLFCT_glMakeNamedBufferNonResidentNV
typedef void (APIENTRYP PFNGLUXMAKENAMEDBUFFERNONRESIDENTNVPROC) (GLuint buffer);
#endif
#ifndef __GLUX__GLFCT_glIsNamedBufferResidentNV
typedef GLboolean (APIENTRYP PFNGLUXISNAMEDBUFFERRESIDENTNVPROC) (GLuint buffer);
#endif
#ifndef __GLUX__GLFCT_glGetBufferParameterui64vNV
typedef void (APIENTRYP PFNGLUXGETBUFFERPARAMETERUI64VNVPROC) (GLenum target, GLenum pname, GLuint64EXT *params);
#endif
#ifndef __GLUX__GLFCT_glGetNamedBufferParameterui64vNV
typedef void (APIENTRYP PFNGLUXGETNAMEDBUFFERPARAMETERUI64VNVPROC) (GLuint buffer, GLenum pname, GLuint64EXT *params);
#endif
#ifndef __GLUX__GLFCT_glGetIntegerui64vNV
typedef void (APIENTRYP PFNGLUXGETINTEGERUI64VNVPROC) (GLenum value, GLuint64EXT *result);
#endif
#ifndef __GLUX__GLFCT_glUniformui64NV
typedef void (APIENTRYP PFNGLUXUNIFORMUI64NVPROC) (GLint location, GLuint64EXT value);
#endif
#ifndef __GLUX__GLFCT_glUniformui64vNV
typedef void (APIENTRYP PFNGLUXUNIFORMUI64VNVPROC) (GLint location, GLsizei count, const GLuint64EXT *value);
#endif
#ifndef __GLUX__GLFCT_glProgramUniformui64NV
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORMUI64NVPROC) (GLuint program, GLint location, GLuint64EXT value);
#endif
#ifndef __GLUX__GLFCT_glProgramUniformui64vNV
typedef void (APIENTRYP PFNGLUXPROGRAMUNIFORMUI64VNVPROC) (GLuint program, GLint location, GLsizei count, const GLuint64EXT *value);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glMakeBufferResidentNV
extern PFNGLUXMAKEBUFFERRESIDENTNVPROC glMakeBufferResidentNV;
#endif
#ifndef __GLUX__GLFCT_glMakeBufferNonResidentNV
extern PFNGLUXMAKEBUFFERNONRESIDENTNVPROC glMakeBufferNonResidentNV;
#endif
#ifndef __GLUX__GLFCT_glIsBufferResidentNV
extern PFNGLUXISBUFFERRESIDENTNVPROC glIsBufferResidentNV;
#endif
#ifndef __GLUX__GLFCT_glMakeNamedBufferResidentNV
extern PFNGLUXMAKENAMEDBUFFERRESIDENTNVPROC glMakeNamedBufferResidentNV;
#endif
#ifndef __GLUX__GLFCT_glMakeNamedBufferNonResidentNV
extern PFNGLUXMAKENAMEDBUFFERNONRESIDENTNVPROC glMakeNamedBufferNonResidentNV;
#endif
#ifndef __GLUX__GLFCT_glIsNamedBufferResidentNV
extern PFNGLUXISNAMEDBUFFERRESIDENTNVPROC glIsNamedBufferResidentNV;
#endif
#ifndef __GLUX__GLFCT_glGetBufferParameterui64vNV
extern PFNGLUXGETBUFFERPARAMETERUI64VNVPROC glGetBufferParameterui64vNV;
#endif
#ifndef __GLUX__GLFCT_glGetNamedBufferParameterui64vNV
extern PFNGLUXGETNAMEDBUFFERPARAMETERUI64VNVPROC glGetNamedBufferParameterui64vNV;
#endif
#ifndef __GLUX__GLFCT_glGetIntegerui64vNV
extern PFNGLUXGETINTEGERUI64VNVPROC glGetIntegerui64vNV;
#endif
#ifndef __GLUX__GLFCT_glUniformui64NV
extern PFNGLUXUNIFORMUI64NVPROC glUniformui64NV;
#endif
#ifndef __GLUX__GLFCT_glUniformui64vNV
extern PFNGLUXUNIFORMUI64VNVPROC glUniformui64vNV;
#endif
#ifndef __GLUX__GLFCT_glProgramUniformui64NV
extern PFNGLUXPROGRAMUNIFORMUI64NVPROC glProgramUniformui64NV;
#endif
#ifndef __GLUX__GLFCT_glProgramUniformui64vNV
extern PFNGLUXPROGRAMUNIFORMUI64VNVPROC glProgramUniformui64vNV;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
