
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_gpu_program4__
#define __GLUX_GL_NV_gpu_program4__

GLUX_NEW_PLUGIN(GL_NV_gpu_program4)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_MIN_PROGRAM_TEXEL_OFFSET_NV
#    define GL_MIN_PROGRAM_TEXEL_OFFSET_NV 0x8904
#  endif
#  ifndef GL_MAX_PROGRAM_TEXEL_OFFSET_NV
#    define GL_MAX_PROGRAM_TEXEL_OFFSET_NV 0x8905
#  endif
#  ifndef GL_PROGRAM_ATTRIB_COMPONENTS_NV
#    define GL_PROGRAM_ATTRIB_COMPONENTS_NV 0x8906
#  endif
#  ifndef GL_PROGRAM_RESULT_COMPONENTS_NV
#    define GL_PROGRAM_RESULT_COMPONENTS_NV 0x8907
#  endif
#  ifndef GL_MAX_PROGRAM_ATTRIB_COMPONENTS_NV
#    define GL_MAX_PROGRAM_ATTRIB_COMPONENTS_NV 0x8908
#  endif
#  ifndef GL_MAX_PROGRAM_RESULT_COMPONENTS_NV
#    define GL_MAX_PROGRAM_RESULT_COMPONENTS_NV 0x8909
#  endif
#  ifndef GL_MAX_PROGRAM_GENERIC_ATTRIBS_NV
#    define GL_MAX_PROGRAM_GENERIC_ATTRIBS_NV 0x8DA5
#  endif
#  ifndef GL_MAX_PROGRAM_GENERIC_RESULTS_NV
#    define GL_MAX_PROGRAM_GENERIC_RESULTS_NV 0x8DA6
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glProgramLocalParameterI4iNV
typedef void (APIENTRYP PFNGLUXPROGRAMLOCALPARAMETERI4INVPROC) (GLenum target, GLuint index, GLint x, GLint y, GLint z, GLint w);
#endif
#ifndef __GLUX__GLFCT_glProgramLocalParameterI4ivNV
typedef void (APIENTRYP PFNGLUXPROGRAMLOCALPARAMETERI4IVNVPROC) (GLenum target, GLuint index, const GLint *params);
#endif
#ifndef __GLUX__GLFCT_glProgramLocalParametersI4ivNV
typedef void (APIENTRYP PFNGLUXPROGRAMLOCALPARAMETERSI4IVNVPROC) (GLenum target, GLuint index, GLsizei count, const GLint *params);
#endif
#ifndef __GLUX__GLFCT_glProgramLocalParameterI4uiNV
typedef void (APIENTRYP PFNGLUXPROGRAMLOCALPARAMETERI4UINVPROC) (GLenum target, GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
#endif
#ifndef __GLUX__GLFCT_glProgramLocalParameterI4uivNV
typedef void (APIENTRYP PFNGLUXPROGRAMLOCALPARAMETERI4UIVNVPROC) (GLenum target, GLuint index, const GLuint *params);
#endif
#ifndef __GLUX__GLFCT_glProgramLocalParametersI4uivNV
typedef void (APIENTRYP PFNGLUXPROGRAMLOCALPARAMETERSI4UIVNVPROC) (GLenum target, GLuint index, GLsizei count, const GLuint *params);
#endif
#ifndef __GLUX__GLFCT_glProgramEnvParameterI4iNV
typedef void (APIENTRYP PFNGLUXPROGRAMENVPARAMETERI4INVPROC) (GLenum target, GLuint index, GLint x, GLint y, GLint z, GLint w);
#endif
#ifndef __GLUX__GLFCT_glProgramEnvParameterI4ivNV
typedef void (APIENTRYP PFNGLUXPROGRAMENVPARAMETERI4IVNVPROC) (GLenum target, GLuint index, const GLint *params);
#endif
#ifndef __GLUX__GLFCT_glProgramEnvParametersI4ivNV
typedef void (APIENTRYP PFNGLUXPROGRAMENVPARAMETERSI4IVNVPROC) (GLenum target, GLuint index, GLsizei count, const GLint *params);
#endif
#ifndef __GLUX__GLFCT_glProgramEnvParameterI4uiNV
typedef void (APIENTRYP PFNGLUXPROGRAMENVPARAMETERI4UINVPROC) (GLenum target, GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
#endif
#ifndef __GLUX__GLFCT_glProgramEnvParameterI4uivNV
typedef void (APIENTRYP PFNGLUXPROGRAMENVPARAMETERI4UIVNVPROC) (GLenum target, GLuint index, const GLuint *params);
#endif
#ifndef __GLUX__GLFCT_glProgramEnvParametersI4uivNV
typedef void (APIENTRYP PFNGLUXPROGRAMENVPARAMETERSI4UIVNVPROC) (GLenum target, GLuint index, GLsizei count, const GLuint *params);
#endif
#ifndef __GLUX__GLFCT_glGetProgramLocalParameterIivNV
typedef void (APIENTRYP PFNGLUXGETPROGRAMLOCALPARAMETERIIVNVPROC) (GLenum target, GLuint index, GLint *params);
#endif
#ifndef __GLUX__GLFCT_glGetProgramLocalParameterIuivNV
typedef void (APIENTRYP PFNGLUXGETPROGRAMLOCALPARAMETERIUIVNVPROC) (GLenum target, GLuint index, GLuint *params);
#endif
#ifndef __GLUX__GLFCT_glGetProgramEnvParameterIivNV
typedef void (APIENTRYP PFNGLUXGETPROGRAMENVPARAMETERIIVNVPROC) (GLenum target, GLuint index, GLint *params);
#endif
#ifndef __GLUX__GLFCT_glGetProgramEnvParameterIuivNV
typedef void (APIENTRYP PFNGLUXGETPROGRAMENVPARAMETERIUIVNVPROC) (GLenum target, GLuint index, GLuint *params);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glProgramLocalParameterI4iNV
extern PFNGLUXPROGRAMLOCALPARAMETERI4INVPROC glProgramLocalParameterI4iNV;
#endif
#ifndef __GLUX__GLFCT_glProgramLocalParameterI4ivNV
extern PFNGLUXPROGRAMLOCALPARAMETERI4IVNVPROC glProgramLocalParameterI4ivNV;
#endif
#ifndef __GLUX__GLFCT_glProgramLocalParametersI4ivNV
extern PFNGLUXPROGRAMLOCALPARAMETERSI4IVNVPROC glProgramLocalParametersI4ivNV;
#endif
#ifndef __GLUX__GLFCT_glProgramLocalParameterI4uiNV
extern PFNGLUXPROGRAMLOCALPARAMETERI4UINVPROC glProgramLocalParameterI4uiNV;
#endif
#ifndef __GLUX__GLFCT_glProgramLocalParameterI4uivNV
extern PFNGLUXPROGRAMLOCALPARAMETERI4UIVNVPROC glProgramLocalParameterI4uivNV;
#endif
#ifndef __GLUX__GLFCT_glProgramLocalParametersI4uivNV
extern PFNGLUXPROGRAMLOCALPARAMETERSI4UIVNVPROC glProgramLocalParametersI4uivNV;
#endif
#ifndef __GLUX__GLFCT_glProgramEnvParameterI4iNV
extern PFNGLUXPROGRAMENVPARAMETERI4INVPROC glProgramEnvParameterI4iNV;
#endif
#ifndef __GLUX__GLFCT_glProgramEnvParameterI4ivNV
extern PFNGLUXPROGRAMENVPARAMETERI4IVNVPROC glProgramEnvParameterI4ivNV;
#endif
#ifndef __GLUX__GLFCT_glProgramEnvParametersI4ivNV
extern PFNGLUXPROGRAMENVPARAMETERSI4IVNVPROC glProgramEnvParametersI4ivNV;
#endif
#ifndef __GLUX__GLFCT_glProgramEnvParameterI4uiNV
extern PFNGLUXPROGRAMENVPARAMETERI4UINVPROC glProgramEnvParameterI4uiNV;
#endif
#ifndef __GLUX__GLFCT_glProgramEnvParameterI4uivNV
extern PFNGLUXPROGRAMENVPARAMETERI4UIVNVPROC glProgramEnvParameterI4uivNV;
#endif
#ifndef __GLUX__GLFCT_glProgramEnvParametersI4uivNV
extern PFNGLUXPROGRAMENVPARAMETERSI4UIVNVPROC glProgramEnvParametersI4uivNV;
#endif
#ifndef __GLUX__GLFCT_glGetProgramLocalParameterIivNV
extern PFNGLUXGETPROGRAMLOCALPARAMETERIIVNVPROC glGetProgramLocalParameterIivNV;
#endif
#ifndef __GLUX__GLFCT_glGetProgramLocalParameterIuivNV
extern PFNGLUXGETPROGRAMLOCALPARAMETERIUIVNVPROC glGetProgramLocalParameterIuivNV;
#endif
#ifndef __GLUX__GLFCT_glGetProgramEnvParameterIivNV
extern PFNGLUXGETPROGRAMENVPARAMETERIIVNVPROC glGetProgramEnvParameterIivNV;
#endif
#ifndef __GLUX__GLFCT_glGetProgramEnvParameterIuivNV
extern PFNGLUXGETPROGRAMENVPARAMETERIUIVNVPROC glGetProgramEnvParameterIuivNV;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
