
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_present_video__
#define __GLUX_GL_NV_present_video__

GLUX_NEW_PLUGIN(GL_NV_present_video)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_FRAME_NV
#    define GL_FRAME_NV 0x8E26
#  endif
#  ifndef GL_FIELDS_NV
#    define GL_FIELDS_NV 0x8E27
#  endif
#  ifndef GL_CURRENT_TIME_NV
#    define GL_CURRENT_TIME_NV 0x8E28
#  endif
#  ifndef GL_NUM_FILL_STREAMS_NV
#    define GL_NUM_FILL_STREAMS_NV 0x8E29
#  endif
#  ifndef GL_PRESENT_TIME_NV
#    define GL_PRESENT_TIME_NV 0x8E2A
#  endif
#  ifndef GL_PRESENT_DURATION_NV
#    define GL_PRESENT_DURATION_NV 0x8E2B
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glPresentFrameKeyedNV
typedef void (APIENTRYP PFNGLUXPRESENTFRAMEKEYEDNVPROC) (GLuint video_slot, GLuint64EXT minPresentTime, GLuint beginPresentTimeId, GLuint presentDurationId, GLenum type, GLenum target0, GLuint fill0, GLuint key0, GLenum target1, GLuint fill1, GLuint key1);
#endif
#ifndef __GLUX__GLFCT_glPresentFrameDualFillNV
typedef void (APIENTRYP PFNGLUXPRESENTFRAMEDUALFILLNVPROC) (GLuint video_slot, GLuint64EXT minPresentTime, GLuint beginPresentTimeId, GLuint presentDurationId, GLenum type, GLenum target0, GLuint fill0, GLenum target1, GLuint fill1, GLenum target2, GLuint fill2, GLenum target3, GLuint fill3);
#endif
#ifndef __GLUX__GLFCT_glGetVideoivNV
typedef void (APIENTRYP PFNGLUXGETVIDEOIVNVPROC) (GLuint video_slot, GLenum pname, GLint *params);
#endif
#ifndef __GLUX__GLFCT_glGetVideouivNV
typedef void (APIENTRYP PFNGLUXGETVIDEOUIVNVPROC) (GLuint video_slot, GLenum pname, GLuint *params);
#endif
#ifndef __GLUX__GLFCT_glGetVideoi64vNV
typedef void (APIENTRYP PFNGLUXGETVIDEOI64VNVPROC) (GLuint video_slot, GLenum pname, GLint64EXT *params);
#endif
#ifndef __GLUX__GLFCT_glGetVideoui64vNV
typedef void (APIENTRYP PFNGLUXGETVIDEOUI64VNVPROC) (GLuint video_slot, GLenum pname, GLuint64EXT *params);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glPresentFrameKeyedNV
extern PFNGLUXPRESENTFRAMEKEYEDNVPROC glPresentFrameKeyedNV;
#endif
#ifndef __GLUX__GLFCT_glPresentFrameDualFillNV
extern PFNGLUXPRESENTFRAMEDUALFILLNVPROC glPresentFrameDualFillNV;
#endif
#ifndef __GLUX__GLFCT_glGetVideoivNV
extern PFNGLUXGETVIDEOIVNVPROC glGetVideoivNV;
#endif
#ifndef __GLUX__GLFCT_glGetVideouivNV
extern PFNGLUXGETVIDEOUIVNVPROC glGetVideouivNV;
#endif
#ifndef __GLUX__GLFCT_glGetVideoi64vNV
extern PFNGLUXGETVIDEOI64VNVPROC glGetVideoi64vNV;
#endif
#ifndef __GLUX__GLFCT_glGetVideoui64vNV
extern PFNGLUXGETVIDEOUI64VNVPROC glGetVideoui64vNV;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
