
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:03 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NVX_linked_gpu_multicast__
#define __GLUX_GL_NVX_linked_gpu_multicast__

GLUX_NEW_PLUGIN(GL_NVX_linked_gpu_multicast)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_LGPU_SEPARATE_STORAGE_BIT_NVX
#    define GL_LGPU_SEPARATE_STORAGE_BIT_NVX 0x0800
#  endif
#  ifndef GL_MAX_LGPU_GPUS_NVX
#    define GL_MAX_LGPU_GPUS_NVX 0x92BA
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glLGPUNamedBufferSubDataNVX
typedef void (APIENTRYP PFNGLUXLGPUNAMEDBUFFERSUBDATANVXPROC) (GLbitfield gpuMask, GLuint buffer, GLintptr offset, GLsizeiptr size, const void *data);
#endif
#ifndef __GLUX__GLFCT_glLGPUCopyImageSubDataNVX
typedef void (APIENTRYP PFNGLUXLGPUCOPYIMAGESUBDATANVXPROC) (GLuint sourceGpu, GLbitfield destinationGpuMask, GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srxY, GLint srcZ, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei width, GLsizei height, GLsizei depth);
#endif
#ifndef __GLUX__GLFCT_glLGPUInterlockNVX
typedef void (APIENTRYP PFNGLUXLGPUINTERLOCKNVXPROC) (void);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glLGPUNamedBufferSubDataNVX
extern PFNGLUXLGPUNAMEDBUFFERSUBDATANVXPROC glLGPUNamedBufferSubDataNVX;
#endif
#ifndef __GLUX__GLFCT_glLGPUCopyImageSubDataNVX
extern PFNGLUXLGPUCOPYIMAGESUBDATANVXPROC glLGPUCopyImageSubDataNVX;
#endif
#ifndef __GLUX__GLFCT_glLGPUInterlockNVX
extern PFNGLUXLGPUINTERLOCKNVXPROC glLGPUInterlockNVX;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
