
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_conditional_render__
#define __GLUX_GL_NV_conditional_render__

GLUX_NEW_PLUGIN(GL_NV_conditional_render)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_QUERY_WAIT_NV
#    define GL_QUERY_WAIT_NV 0x8E13
#  endif
#  ifndef GL_QUERY_NO_WAIT_NV
#    define GL_QUERY_NO_WAIT_NV 0x8E14
#  endif
#  ifndef GL_QUERY_BY_REGION_WAIT_NV
#    define GL_QUERY_BY_REGION_WAIT_NV 0x8E15
#  endif
#  ifndef GL_QUERY_BY_REGION_NO_WAIT_NV
#    define GL_QUERY_BY_REGION_NO_WAIT_NV 0x8E16
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glBeginConditionalRenderNV
typedef void (APIENTRYP PFNGLUXBEGINCONDITIONALRENDERNVPROC) (GLuint id, GLenum mode);
#endif
#ifndef __GLUX__GLFCT_glEndConditionalRenderNV
typedef void (APIENTRYP PFNGLUXENDCONDITIONALRENDERNVPROC) (void);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glBeginConditionalRenderNV
extern PFNGLUXBEGINCONDITIONALRENDERNVPROC glBeginConditionalRenderNV;
#endif
#ifndef __GLUX__GLFCT_glEndConditionalRenderNV
extern PFNGLUXENDCONDITIONALRENDERNVPROC glEndConditionalRenderNV;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
