
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_internalformat_sample_query__
#define __GLUX_GL_NV_internalformat_sample_query__

GLUX_NEW_PLUGIN(GL_NV_internalformat_sample_query)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_MULTISAMPLES_NV
#    define GL_MULTISAMPLES_NV 0x9371
#  endif
#  ifndef GL_SUPERSAMPLE_SCALE_X_NV
#    define GL_SUPERSAMPLE_SCALE_X_NV 0x9372
#  endif
#  ifndef GL_SUPERSAMPLE_SCALE_Y_NV
#    define GL_SUPERSAMPLE_SCALE_Y_NV 0x9373
#  endif
#  ifndef GL_CONFORMANT_NV
#    define GL_CONFORMANT_NV 0x9374
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glGetInternalformatSampleivNV
typedef void (APIENTRYP PFNGLUXGETINTERNALFORMATSAMPLEIVNVPROC) (GLenum target, GLenum internalformat, GLsizei samples, GLenum pname, GLsizei bufSize, GLint *params);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glGetInternalformatSampleivNV
extern PFNGLUXGETINTERNALFORMATSAMPLEIVNVPROC glGetInternalformatSampleivNV;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
