
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:03 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_geometry_program4__
#define __GLUX_GL_NV_geometry_program4__

GLUX_NEW_PLUGIN(GL_NV_geometry_program4)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_GEOMETRY_PROGRAM_NV
#    define GL_GEOMETRY_PROGRAM_NV 0x8C26
#  endif
#  ifndef GL_MAX_PROGRAM_OUTPUT_VERTICES_NV
#    define GL_MAX_PROGRAM_OUTPUT_VERTICES_NV 0x8C27
#  endif
#  ifndef GL_MAX_PROGRAM_TOTAL_OUTPUT_COMPONENTS_NV
#    define GL_MAX_PROGRAM_TOTAL_OUTPUT_COMPONENTS_NV 0x8C28
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glProgramVertexLimitNV
typedef void (APIENTRYP PFNGLUXPROGRAMVERTEXLIMITNVPROC) (GLenum target, GLint limit);
#endif
#ifndef __GLUX__GLFCT_glFramebufferTextureEXT
typedef void (APIENTRYP PFNGLUXFRAMEBUFFERTEXTUREEXTPROC) (GLenum target, GLenum attachment, GLuint texture, GLint level);
#endif
#ifndef __GLUX__GLFCT_glFramebufferTextureFaceEXT
typedef void (APIENTRYP PFNGLUXFRAMEBUFFERTEXTUREFACEEXTPROC) (GLenum target, GLenum attachment, GLuint texture, GLint level, GLenum face);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glProgramVertexLimitNV
extern PFNGLUXPROGRAMVERTEXLIMITNVPROC glProgramVertexLimitNV;
#endif
#ifndef __GLUX__GLFCT_glFramebufferTextureEXT
extern PFNGLUXFRAMEBUFFERTEXTUREEXTPROC glFramebufferTextureEXT;
#endif
#ifndef __GLUX__GLFCT_glFramebufferTextureFaceEXT
extern PFNGLUXFRAMEBUFFERTEXTUREFACEEXTPROC glFramebufferTextureFaceEXT;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
