
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:03 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_occlusion_query__
#define __GLUX_GL_NV_occlusion_query__

GLUX_NEW_PLUGIN(GL_NV_occlusion_query)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_PIXEL_COUNTER_BITS_NV
#    define GL_PIXEL_COUNTER_BITS_NV 0x8864
#  endif
#  ifndef GL_CURRENT_OCCLUSION_QUERY_ID_NV
#    define GL_CURRENT_OCCLUSION_QUERY_ID_NV 0x8865
#  endif
#  ifndef GL_PIXEL_COUNT_NV
#    define GL_PIXEL_COUNT_NV 0x8866
#  endif
#  ifndef GL_PIXEL_COUNT_AVAILABLE_NV
#    define GL_PIXEL_COUNT_AVAILABLE_NV 0x8867
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glGenOcclusionQueriesNV
typedef void (APIENTRYP PFNGLUXGENOCCLUSIONQUERIESNVPROC) (GLsizei n, GLuint *ids);
#endif
#ifndef __GLUX__GLFCT_glDeleteOcclusionQueriesNV
typedef void (APIENTRYP PFNGLUXDELETEOCCLUSIONQUERIESNVPROC) (GLsizei n, const GLuint *ids);
#endif
#ifndef __GLUX__GLFCT_glIsOcclusionQueryNV
typedef GLboolean (APIENTRYP PFNGLUXISOCCLUSIONQUERYNVPROC) (GLuint id);
#endif
#ifndef __GLUX__GLFCT_glBeginOcclusionQueryNV
typedef void (APIENTRYP PFNGLUXBEGINOCCLUSIONQUERYNVPROC) (GLuint id);
#endif
#ifndef __GLUX__GLFCT_glEndOcclusionQueryNV
typedef void (APIENTRYP PFNGLUXENDOCCLUSIONQUERYNVPROC) (void);
#endif
#ifndef __GLUX__GLFCT_glGetOcclusionQueryivNV
typedef void (APIENTRYP PFNGLUXGETOCCLUSIONQUERYIVNVPROC) (GLuint id, GLenum pname, GLint *params);
#endif
#ifndef __GLUX__GLFCT_glGetOcclusionQueryuivNV
typedef void (APIENTRYP PFNGLUXGETOCCLUSIONQUERYUIVNVPROC) (GLuint id, GLenum pname, GLuint *params);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glGenOcclusionQueriesNV
extern PFNGLUXGENOCCLUSIONQUERIESNVPROC glGenOcclusionQueriesNV;
#endif
#ifndef __GLUX__GLFCT_glDeleteOcclusionQueriesNV
extern PFNGLUXDELETEOCCLUSIONQUERIESNVPROC glDeleteOcclusionQueriesNV;
#endif
#ifndef __GLUX__GLFCT_glIsOcclusionQueryNV
extern PFNGLUXISOCCLUSIONQUERYNVPROC glIsOcclusionQueryNV;
#endif
#ifndef __GLUX__GLFCT_glBeginOcclusionQueryNV
extern PFNGLUXBEGINOCCLUSIONQUERYNVPROC glBeginOcclusionQueryNV;
#endif
#ifndef __GLUX__GLFCT_glEndOcclusionQueryNV
extern PFNGLUXENDOCCLUSIONQUERYNVPROC glEndOcclusionQueryNV;
#endif
#ifndef __GLUX__GLFCT_glGetOcclusionQueryivNV
extern PFNGLUXGETOCCLUSIONQUERYIVNVPROC glGetOcclusionQueryivNV;
#endif
#ifndef __GLUX__GLFCT_glGetOcclusionQueryuivNV
extern PFNGLUXGETOCCLUSIONQUERYUIVNVPROC glGetOcclusionQueryuivNV;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
