
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_texture_shader3__
#define __GLUX_GL_NV_texture_shader3__

GLUX_NEW_PLUGIN(GL_NV_texture_shader3)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_OFFSET_PROJECTIVE_TEXTURE_2D_NV
#    define GL_OFFSET_PROJECTIVE_TEXTURE_2D_NV 0x8850
#  endif
#  ifndef GL_OFFSET_PROJECTIVE_TEXTURE_2D_SCALE_NV
#    define GL_OFFSET_PROJECTIVE_TEXTURE_2D_SCALE_NV 0x8851
#  endif
#  ifndef GL_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_NV
#    define GL_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_NV 0x8852
#  endif
#  ifndef GL_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE_NV
#    define GL_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE_NV 0x8853
#  endif
#  ifndef GL_OFFSET_HILO_TEXTURE_2D_NV
#    define GL_OFFSET_HILO_TEXTURE_2D_NV 0x8854
#  endif
#  ifndef GL_OFFSET_HILO_TEXTURE_RECTANGLE_NV
#    define GL_OFFSET_HILO_TEXTURE_RECTANGLE_NV 0x8855
#  endif
#  ifndef GL_OFFSET_HILO_PROJECTIVE_TEXTURE_2D_NV
#    define GL_OFFSET_HILO_PROJECTIVE_TEXTURE_2D_NV 0x8856
#  endif
#  ifndef GL_OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE_NV
#    define GL_OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE_NV 0x8857
#  endif
#  ifndef GL_DEPENDENT_HILO_TEXTURE_2D_NV
#    define GL_DEPENDENT_HILO_TEXTURE_2D_NV 0x8858
#  endif
#  ifndef GL_DEPENDENT_RGB_TEXTURE_3D_NV
#    define GL_DEPENDENT_RGB_TEXTURE_3D_NV 0x8859
#  endif
#  ifndef GL_DEPENDENT_RGB_TEXTURE_CUBE_MAP_NV
#    define GL_DEPENDENT_RGB_TEXTURE_CUBE_MAP_NV 0x885A
#  endif
#  ifndef GL_DOT_PRODUCT_PASS_THROUGH_NV
#    define GL_DOT_PRODUCT_PASS_THROUGH_NV 0x885B
#  endif
#  ifndef GL_DOT_PRODUCT_TEXTURE_1D_NV
#    define GL_DOT_PRODUCT_TEXTURE_1D_NV 0x885C
#  endif
#  ifndef GL_DOT_PRODUCT_AFFINE_DEPTH_REPLACE_NV
#    define GL_DOT_PRODUCT_AFFINE_DEPTH_REPLACE_NV 0x885D
#  endif
#  ifndef GL_HILO8_NV
#    define GL_HILO8_NV 0x885E
#  endif
#  ifndef GL_SIGNED_HILO8_NV
#    define GL_SIGNED_HILO8_NV 0x885F
#  endif
#  ifndef GL_FORCE_BLUE_TO_ONE_NV
#    define GL_FORCE_BLUE_TO_ONE_NV 0x8860
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
