
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:03 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_texture_env_combine4__
#define __GLUX_GL_NV_texture_env_combine4__

GLUX_NEW_PLUGIN(GL_NV_texture_env_combine4)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_COMBINE4_NV
#    define GL_COMBINE4_NV 0x8503
#  endif
#  ifndef GL_SOURCE3_RGB_NV
#    define GL_SOURCE3_RGB_NV 0x8583
#  endif
#  ifndef GL_SOURCE3_ALPHA_NV
#    define GL_SOURCE3_ALPHA_NV 0x858B
#  endif
#  ifndef GL_OPERAND3_RGB_NV
#    define GL_OPERAND3_RGB_NV 0x8593
#  endif
#  ifndef GL_OPERAND3_ALPHA_NV
#    define GL_OPERAND3_ALPHA_NV 0x859B
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
