
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_NV_gpu_program5__
#define __GLUX_GL_NV_gpu_program5__

GLUX_NEW_PLUGIN(GL_NV_gpu_program5)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_MAX_GEOMETRY_PROGRAM_INVOCATIONS_NV
#    define GL_MAX_GEOMETRY_PROGRAM_INVOCATIONS_NV 0x8E5A
#  endif
#  ifndef GL_MIN_FRAGMENT_INTERPOLATION_OFFSET_NV
#    define GL_MIN_FRAGMENT_INTERPOLATION_OFFSET_NV 0x8E5B
#  endif
#  ifndef GL_MAX_FRAGMENT_INTERPOLATION_OFFSET_NV
#    define GL_MAX_FRAGMENT_INTERPOLATION_OFFSET_NV 0x8E5C
#  endif
#  ifndef GL_FRAGMENT_PROGRAM_INTERPOLATION_OFFSET_BITS_NV
#    define GL_FRAGMENT_PROGRAM_INTERPOLATION_OFFSET_BITS_NV 0x8E5D
#  endif
#  ifndef GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET_NV
#    define GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET_NV 0x8E5E
#  endif
#  ifndef GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET_NV
#    define GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET_NV 0x8E5F
#  endif
#  ifndef GL_MAX_PROGRAM_SUBROUTINE_PARAMETERS_NV
#    define GL_MAX_PROGRAM_SUBROUTINE_PARAMETERS_NV 0x8F44
#  endif
#  ifndef GL_MAX_PROGRAM_SUBROUTINE_NUM_NV
#    define GL_MAX_PROGRAM_SUBROUTINE_NUM_NV 0x8F45
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glProgramSubroutineParametersuivNV
typedef void (APIENTRYP PFNGLUXPROGRAMSUBROUTINEPARAMETERSUIVNVPROC) (GLenum target, GLsizei count, const GLuint *params);
#endif
#ifndef __GLUX__GLFCT_glGetProgramSubroutineParameteruivNV
typedef void (APIENTRYP PFNGLUXGETPROGRAMSUBROUTINEPARAMETERUIVNVPROC) (GLenum target, GLuint index, GLuint *param);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glProgramSubroutineParametersuivNV
extern PFNGLUXPROGRAMSUBROUTINEPARAMETERSUIVNVPROC glProgramSubroutineParametersuivNV;
#endif
#ifndef __GLUX__GLFCT_glGetProgramSubroutineParameteruivNV
extern PFNGLUXGETPROGRAMSUBROUTINEPARAMETERUIVNVPROC glGetProgramSubroutineParameteruivNV;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
