
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_OML_resample__
#define __GLUX_GL_OML_resample__

GLUX_NEW_PLUGIN(GL_OML_resample)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_PACK_RESAMPLE_OML
#    define GL_PACK_RESAMPLE_OML 0x8984
#  endif
#  ifndef GL_UNPACK_RESAMPLE_OML
#    define GL_UNPACK_RESAMPLE_OML 0x8985
#  endif
#  ifndef GL_RESAMPLE_REPLICATE_OML
#    define GL_RESAMPLE_REPLICATE_OML 0x8986
#  endif
#  ifndef GL_RESAMPLE_ZERO_FILL_OML
#    define GL_RESAMPLE_ZERO_FILL_OML 0x8987
#  endif
#  ifndef GL_RESAMPLE_AVERAGE_OML
#    define GL_RESAMPLE_AVERAGE_OML 0x8988
#  endif
#  ifndef GL_RESAMPLE_DECIMATE_OML
#    define GL_RESAMPLE_DECIMATE_OML 0x8989
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
