
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_OES_byte_coordinates__
#define __GLUX_GL_OES_byte_coordinates__

GLUX_NEW_PLUGIN(GL_OES_byte_coordinates)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glMultiTexCoord1bOES
typedef void (APIENTRYP PFNGLUXMULTITEXCOORD1BOESPROC) (GLenum texture, GLbyte s);
#endif
#ifndef __GLUX__GLFCT_glMultiTexCoord1bvOES
typedef void (APIENTRYP PFNGLUXMULTITEXCOORD1BVOESPROC) (GLenum texture, const GLbyte *coords);
#endif
#ifndef __GLUX__GLFCT_glMultiTexCoord2bOES
typedef void (APIENTRYP PFNGLUXMULTITEXCOORD2BOESPROC) (GLenum texture, GLbyte s, GLbyte t);
#endif
#ifndef __GLUX__GLFCT_glMultiTexCoord2bvOES
typedef void (APIENTRYP PFNGLUXMULTITEXCOORD2BVOESPROC) (GLenum texture, const GLbyte *coords);
#endif
#ifndef __GLUX__GLFCT_glMultiTexCoord3bOES
typedef void (APIENTRYP PFNGLUXMULTITEXCOORD3BOESPROC) (GLenum texture, GLbyte s, GLbyte t, GLbyte r);
#endif
#ifndef __GLUX__GLFCT_glMultiTexCoord3bvOES
typedef void (APIENTRYP PFNGLUXMULTITEXCOORD3BVOESPROC) (GLenum texture, const GLbyte *coords);
#endif
#ifndef __GLUX__GLFCT_glMultiTexCoord4bOES
typedef void (APIENTRYP PFNGLUXMULTITEXCOORD4BOESPROC) (GLenum texture, GLbyte s, GLbyte t, GLbyte r, GLbyte q);
#endif
#ifndef __GLUX__GLFCT_glMultiTexCoord4bvOES
typedef void (APIENTRYP PFNGLUXMULTITEXCOORD4BVOESPROC) (GLenum texture, const GLbyte *coords);
#endif
#ifndef __GLUX__GLFCT_glTexCoord1bOES
typedef void (APIENTRYP PFNGLUXTEXCOORD1BOESPROC) (GLbyte s);
#endif
#ifndef __GLUX__GLFCT_glTexCoord1bvOES
typedef void (APIENTRYP PFNGLUXTEXCOORD1BVOESPROC) (const GLbyte *coords);
#endif
#ifndef __GLUX__GLFCT_glTexCoord2bOES
typedef void (APIENTRYP PFNGLUXTEXCOORD2BOESPROC) (GLbyte s, GLbyte t);
#endif
#ifndef __GLUX__GLFCT_glTexCoord2bvOES
typedef void (APIENTRYP PFNGLUXTEXCOORD2BVOESPROC) (const GLbyte *coords);
#endif
#ifndef __GLUX__GLFCT_glTexCoord3bOES
typedef void (APIENTRYP PFNGLUXTEXCOORD3BOESPROC) (GLbyte s, GLbyte t, GLbyte r);
#endif
#ifndef __GLUX__GLFCT_glTexCoord3bvOES
typedef void (APIENTRYP PFNGLUXTEXCOORD3BVOESPROC) (const GLbyte *coords);
#endif
#ifndef __GLUX__GLFCT_glTexCoord4bOES
typedef void (APIENTRYP PFNGLUXTEXCOORD4BOESPROC) (GLbyte s, GLbyte t, GLbyte r, GLbyte q);
#endif
#ifndef __GLUX__GLFCT_glTexCoord4bvOES
typedef void (APIENTRYP PFNGLUXTEXCOORD4BVOESPROC) (const GLbyte *coords);
#endif
#ifndef __GLUX__GLFCT_glVertex2bOES
typedef void (APIENTRYP PFNGLUXVERTEX2BOESPROC) (GLbyte x, GLbyte y);
#endif
#ifndef __GLUX__GLFCT_glVertex2bvOES
typedef void (APIENTRYP PFNGLUXVERTEX2BVOESPROC) (const GLbyte *coords);
#endif
#ifndef __GLUX__GLFCT_glVertex3bOES
typedef void (APIENTRYP PFNGLUXVERTEX3BOESPROC) (GLbyte x, GLbyte y, GLbyte z);
#endif
#ifndef __GLUX__GLFCT_glVertex3bvOES
typedef void (APIENTRYP PFNGLUXVERTEX3BVOESPROC) (const GLbyte *coords);
#endif
#ifndef __GLUX__GLFCT_glVertex4bOES
typedef void (APIENTRYP PFNGLUXVERTEX4BOESPROC) (GLbyte x, GLbyte y, GLbyte z, GLbyte w);
#endif
#ifndef __GLUX__GLFCT_glVertex4bvOES
typedef void (APIENTRYP PFNGLUXVERTEX4BVOESPROC) (const GLbyte *coords);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glMultiTexCoord1bOES
extern PFNGLUXMULTITEXCOORD1BOESPROC glMultiTexCoord1bOES;
#endif
#ifndef __GLUX__GLFCT_glMultiTexCoord1bvOES
extern PFNGLUXMULTITEXCOORD1BVOESPROC glMultiTexCoord1bvOES;
#endif
#ifndef __GLUX__GLFCT_glMultiTexCoord2bOES
extern PFNGLUXMULTITEXCOORD2BOESPROC glMultiTexCoord2bOES;
#endif
#ifndef __GLUX__GLFCT_glMultiTexCoord2bvOES
extern PFNGLUXMULTITEXCOORD2BVOESPROC glMultiTexCoord2bvOES;
#endif
#ifndef __GLUX__GLFCT_glMultiTexCoord3bOES
extern PFNGLUXMULTITEXCOORD3BOESPROC glMultiTexCoord3bOES;
#endif
#ifndef __GLUX__GLFCT_glMultiTexCoord3bvOES
extern PFNGLUXMULTITEXCOORD3BVOESPROC glMultiTexCoord3bvOES;
#endif
#ifndef __GLUX__GLFCT_glMultiTexCoord4bOES
extern PFNGLUXMULTITEXCOORD4BOESPROC glMultiTexCoord4bOES;
#endif
#ifndef __GLUX__GLFCT_glMultiTexCoord4bvOES
extern PFNGLUXMULTITEXCOORD4BVOESPROC glMultiTexCoord4bvOES;
#endif
#ifndef __GLUX__GLFCT_glTexCoord1bOES
extern PFNGLUXTEXCOORD1BOESPROC glTexCoord1bOES;
#endif
#ifndef __GLUX__GLFCT_glTexCoord1bvOES
extern PFNGLUXTEXCOORD1BVOESPROC glTexCoord1bvOES;
#endif
#ifndef __GLUX__GLFCT_glTexCoord2bOES
extern PFNGLUXTEXCOORD2BOESPROC glTexCoord2bOES;
#endif
#ifndef __GLUX__GLFCT_glTexCoord2bvOES
extern PFNGLUXTEXCOORD2BVOESPROC glTexCoord2bvOES;
#endif
#ifndef __GLUX__GLFCT_glTexCoord3bOES
extern PFNGLUXTEXCOORD3BOESPROC glTexCoord3bOES;
#endif
#ifndef __GLUX__GLFCT_glTexCoord3bvOES
extern PFNGLUXTEXCOORD3BVOESPROC glTexCoord3bvOES;
#endif
#ifndef __GLUX__GLFCT_glTexCoord4bOES
extern PFNGLUXTEXCOORD4BOESPROC glTexCoord4bOES;
#endif
#ifndef __GLUX__GLFCT_glTexCoord4bvOES
extern PFNGLUXTEXCOORD4BVOESPROC glTexCoord4bvOES;
#endif
#ifndef __GLUX__GLFCT_glVertex2bOES
extern PFNGLUXVERTEX2BOESPROC glVertex2bOES;
#endif
#ifndef __GLUX__GLFCT_glVertex2bvOES
extern PFNGLUXVERTEX2BVOESPROC glVertex2bvOES;
#endif
#ifndef __GLUX__GLFCT_glVertex3bOES
extern PFNGLUXVERTEX3BOESPROC glVertex3bOES;
#endif
#ifndef __GLUX__GLFCT_glVertex3bvOES
extern PFNGLUXVERTEX3BVOESPROC glVertex3bvOES;
#endif
#ifndef __GLUX__GLFCT_glVertex4bOES
extern PFNGLUXVERTEX4BOESPROC glVertex4bOES;
#endif
#ifndef __GLUX__GLFCT_glVertex4bvOES
extern PFNGLUXVERTEX4BVOESPROC glVertex4bvOES;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
