
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_PGI_misc_hints__
#define __GLUX_GL_PGI_misc_hints__

GLUX_NEW_PLUGIN(GL_PGI_misc_hints)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_PREFER_DOUBLEBUFFER_HINT_PGI
#    define GL_PREFER_DOUBLEBUFFER_HINT_PGI 0x1A1F8
#  endif
#  ifndef GL_CONSERVE_MEMORY_HINT_PGI
#    define GL_CONSERVE_MEMORY_HINT_PGI 0x1A1FD
#  endif
#  ifndef GL_RECLAIM_MEMORY_HINT_PGI
#    define GL_RECLAIM_MEMORY_HINT_PGI 0x1A1FE
#  endif
#  ifndef GL_NATIVE_GRAPHICS_HANDLE_PGI
#    define GL_NATIVE_GRAPHICS_HANDLE_PGI 0x1A202
#  endif
#  ifndef GL_NATIVE_GRAPHICS_BEGIN_HINT_PGI
#    define GL_NATIVE_GRAPHICS_BEGIN_HINT_PGI 0x1A203
#  endif
#  ifndef GL_NATIVE_GRAPHICS_END_HINT_PGI
#    define GL_NATIVE_GRAPHICS_END_HINT_PGI 0x1A204
#  endif
#  ifndef GL_ALWAYS_FAST_HINT_PGI
#    define GL_ALWAYS_FAST_HINT_PGI 0x1A20C
#  endif
#  ifndef GL_ALWAYS_SOFT_HINT_PGI
#    define GL_ALWAYS_SOFT_HINT_PGI 0x1A20D
#  endif
#  ifndef GL_ALLOW_DRAW_OBJ_HINT_PGI
#    define GL_ALLOW_DRAW_OBJ_HINT_PGI 0x1A20E
#  endif
#  ifndef GL_ALLOW_DRAW_WIN_HINT_PGI
#    define GL_ALLOW_DRAW_WIN_HINT_PGI 0x1A20F
#  endif
#  ifndef GL_ALLOW_DRAW_FRG_HINT_PGI
#    define GL_ALLOW_DRAW_FRG_HINT_PGI 0x1A210
#  endif
#  ifndef GL_ALLOW_DRAW_MEM_HINT_PGI
#    define GL_ALLOW_DRAW_MEM_HINT_PGI 0x1A211
#  endif
#  ifndef GL_STRICT_DEPTHFUNC_HINT_PGI
#    define GL_STRICT_DEPTHFUNC_HINT_PGI 0x1A216
#  endif
#  ifndef GL_STRICT_LIGHTING_HINT_PGI
#    define GL_STRICT_LIGHTING_HINT_PGI 0x1A217
#  endif
#  ifndef GL_STRICT_SCISSOR_HINT_PGI
#    define GL_STRICT_SCISSOR_HINT_PGI 0x1A218
#  endif
#  ifndef GL_FULL_STIPPLE_HINT_PGI
#    define GL_FULL_STIPPLE_HINT_PGI 0x1A219
#  endif
#  ifndef GL_CLIP_NEAR_HINT_PGI
#    define GL_CLIP_NEAR_HINT_PGI 0x1A220
#  endif
#  ifndef GL_CLIP_FAR_HINT_PGI
#    define GL_CLIP_FAR_HINT_PGI 0x1A221
#  endif
#  ifndef GL_WIDE_LINE_HINT_PGI
#    define GL_WIDE_LINE_HINT_PGI 0x1A222
#  endif
#  ifndef GL_BACK_NORMALS_HINT_PGI
#    define GL_BACK_NORMALS_HINT_PGI 0x1A223
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glHintPGI
typedef void (APIENTRYP PFNGLUXHINTPGIPROC) (GLenum target, GLint mode);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glHintPGI
extern PFNGLUXHINTPGIPROC glHintPGI;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
