
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIX_resample__
#define __GLUX_GL_SGIX_resample__

GLUX_NEW_PLUGIN(GL_SGIX_resample)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_PACK_RESAMPLE_SGIX
#    define GL_PACK_RESAMPLE_SGIX 0x842E
#  endif
#  ifndef GL_UNPACK_RESAMPLE_SGIX
#    define GL_UNPACK_RESAMPLE_SGIX 0x842F
#  endif
#  ifndef GL_RESAMPLE_REPLICATE_SGIX
#    define GL_RESAMPLE_REPLICATE_SGIX 0x8433
#  endif
#  ifndef GL_RESAMPLE_ZERO_FILL_SGIX
#    define GL_RESAMPLE_ZERO_FILL_SGIX 0x8434
#  endif
#  ifndef GL_RESAMPLE_DECIMATE_SGIX
#    define GL_RESAMPLE_DECIMATE_SGIX 0x8430
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
