
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIS_detail_texture__
#define __GLUX_GL_SGIS_detail_texture__

GLUX_NEW_PLUGIN(GL_SGIS_detail_texture)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_DETAIL_TEXTURE_2D_SGIS
#    define GL_DETAIL_TEXTURE_2D_SGIS 0x8095
#  endif
#  ifndef GL_DETAIL_TEXTURE_2D_BINDING_SGIS
#    define GL_DETAIL_TEXTURE_2D_BINDING_SGIS 0x8096
#  endif
#  ifndef GL_LINEAR_DETAIL_SGIS
#    define GL_LINEAR_DETAIL_SGIS 0x8097
#  endif
#  ifndef GL_LINEAR_DETAIL_ALPHA_SGIS
#    define GL_LINEAR_DETAIL_ALPHA_SGIS 0x8098
#  endif
#  ifndef GL_LINEAR_DETAIL_COLOR_SGIS
#    define GL_LINEAR_DETAIL_COLOR_SGIS 0x8099
#  endif
#  ifndef GL_DETAIL_TEXTURE_LEVEL_SGIS
#    define GL_DETAIL_TEXTURE_LEVEL_SGIS 0x809A
#  endif
#  ifndef GL_DETAIL_TEXTURE_MODE_SGIS
#    define GL_DETAIL_TEXTURE_MODE_SGIS 0x809B
#  endif
#  ifndef GL_DETAIL_TEXTURE_FUNC_POINTS_SGIS
#    define GL_DETAIL_TEXTURE_FUNC_POINTS_SGIS 0x809C
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glDetailTexFuncSGIS
typedef void (APIENTRYP PFNGLUXDETAILTEXFUNCSGISPROC) (GLenum target, GLsizei n, const GLfloat *points);
#endif
#ifndef __GLUX__GLFCT_glGetDetailTexFuncSGIS
typedef void (APIENTRYP PFNGLUXGETDETAILTEXFUNCSGISPROC) (GLenum target, GLfloat *points);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glDetailTexFuncSGIS
extern PFNGLUXDETAILTEXFUNCSGISPROC glDetailTexFuncSGIS;
#endif
#ifndef __GLUX__GLFCT_glGetDetailTexFuncSGIS
extern PFNGLUXGETDETAILTEXFUNCSGISPROC glGetDetailTexFuncSGIS;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
