
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:03 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GL_SGIX_clipmap__
#define __GLUX_GL_SGIX_clipmap__

GLUX_NEW_PLUGIN(GL_SGIX_clipmap)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GL_LINEAR_CLIPMAP_LINEAR_SGIX
#    define GL_LINEAR_CLIPMAP_LINEAR_SGIX 0x8170
#  endif
#  ifndef GL_TEXTURE_CLIPMAP_CENTER_SGIX
#    define GL_TEXTURE_CLIPMAP_CENTER_SGIX 0x8171
#  endif
#  ifndef GL_TEXTURE_CLIPMAP_FRAME_SGIX
#    define GL_TEXTURE_CLIPMAP_FRAME_SGIX 0x8172
#  endif
#  ifndef GL_TEXTURE_CLIPMAP_OFFSET_SGIX
#    define GL_TEXTURE_CLIPMAP_OFFSET_SGIX 0x8173
#  endif
#  ifndef GL_TEXTURE_CLIPMAP_VIRTUAL_DEPTH_SGIX
#    define GL_TEXTURE_CLIPMAP_VIRTUAL_DEPTH_SGIX 0x8174
#  endif
#  ifndef GL_TEXTURE_CLIPMAP_LOD_OFFSET_SGIX
#    define GL_TEXTURE_CLIPMAP_LOD_OFFSET_SGIX 0x8175
#  endif
#  ifndef GL_TEXTURE_CLIPMAP_DEPTH_SGIX
#    define GL_TEXTURE_CLIPMAP_DEPTH_SGIX 0x8176
#  endif
#  ifndef GL_MAX_CLIPMAP_DEPTH_SGIX
#    define GL_MAX_CLIPMAP_DEPTH_SGIX 0x8177
#  endif
#  ifndef GL_MAX_CLIPMAP_VIRTUAL_DEPTH_SGIX
#    define GL_MAX_CLIPMAP_VIRTUAL_DEPTH_SGIX 0x8178
#  endif
#  ifndef GL_NEAREST_CLIPMAP_NEAREST_SGIX
#    define GL_NEAREST_CLIPMAP_NEAREST_SGIX 0x844D
#  endif
#  ifndef GL_NEAREST_CLIPMAP_LINEAR_SGIX
#    define GL_NEAREST_CLIPMAP_LINEAR_SGIX 0x844E
#  endif
#  ifndef GL_LINEAR_CLIPMAP_NEAREST_SGIX
#    define GL_LINEAR_CLIPMAP_NEAREST_SGIX 0x844F
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
