
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GLX_EXT_visual_info__
#define __GLUX_GLX_EXT_visual_info__

GLUX_NEW_PLUGIN(GLX_EXT_visual_info)
// --------------------------------------------------------
#if !(defined WIN32 || defined(_WIN64) || defined __APPLE__ || defined EMSCRIPTEN)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GLX_X_VISUAL_TYPE_EXT
#    define GLX_X_VISUAL_TYPE_EXT 0x22
#  endif
#  ifndef GLX_TRANSPARENT_TYPE_EXT
#    define GLX_TRANSPARENT_TYPE_EXT 0x23
#  endif
#  ifndef GLX_TRANSPARENT_INDEX_VALUE_EXT
#    define GLX_TRANSPARENT_INDEX_VALUE_EXT 0x24
#  endif
#  ifndef GLX_TRANSPARENT_RED_VALUE_EXT
#    define GLX_TRANSPARENT_RED_VALUE_EXT 0x25
#  endif
#  ifndef GLX_TRANSPARENT_GREEN_VALUE_EXT
#    define GLX_TRANSPARENT_GREEN_VALUE_EXT 0x26
#  endif
#  ifndef GLX_TRANSPARENT_BLUE_VALUE_EXT
#    define GLX_TRANSPARENT_BLUE_VALUE_EXT 0x27
#  endif
#  ifndef GLX_TRANSPARENT_ALPHA_VALUE_EXT
#    define GLX_TRANSPARENT_ALPHA_VALUE_EXT 0x28
#  endif
#  ifndef GLX_NONE_EXT
#    define GLX_NONE_EXT 0x8000
#  endif
#  ifndef GLX_TRUE_COLOR_EXT
#    define GLX_TRUE_COLOR_EXT 0x8002
#  endif
#  ifndef GLX_DIRECT_COLOR_EXT
#    define GLX_DIRECT_COLOR_EXT 0x8003
#  endif
#  ifndef GLX_PSEUDO_COLOR_EXT
#    define GLX_PSEUDO_COLOR_EXT 0x8004
#  endif
#  ifndef GLX_STATIC_COLOR_EXT
#    define GLX_STATIC_COLOR_EXT 0x8005
#  endif
#  ifndef GLX_GRAY_SCALE_EXT
#    define GLX_GRAY_SCALE_EXT 0x8006
#  endif
#  ifndef GLX_STATIC_GRAY_EXT
#    define GLX_STATIC_GRAY_EXT 0x8007
#  endif
#  ifndef GLX_TRANSPARENT_RGB_EXT
#    define GLX_TRANSPARENT_RGB_EXT 0x8008
#  endif
#  ifndef GLX_TRANSPARENT_INDEX_EXT
#    define GLX_TRANSPARENT_INDEX_EXT 0x8009
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
