
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:03 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GLX_NV_video_capture__
#define __GLUX_GLX_NV_video_capture__

GLUX_NEW_PLUGIN(GLX_NV_video_capture)
// --------------------------------------------------------
#if !(defined WIN32 || defined(_WIN64) || defined __APPLE__ || defined EMSCRIPTEN)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GLX_DEVICE_ID_NV
#    define GLX_DEVICE_ID_NV 0x20CD
#  endif
#  ifndef GLX_UNIQUE_ID_NV
#    define GLX_UNIQUE_ID_NV 0x20CE
#  endif
#  ifndef GLX_NUM_VIDEO_CAPTURE_SLOTS_NV
#    define GLX_NUM_VIDEO_CAPTURE_SLOTS_NV 0x20CF
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glXBindVideoCaptureDeviceNV
typedef int (APIENTRYP PFNXGLUXBINDVIDEOCAPTUREDEVICENVPROC) (Display *dpy, unsigned int video_capture_slot, GLXVideoCaptureDeviceNV device);
#endif
#ifndef __GLUX__GLFCT_glXEnumerateVideoCaptureDevicesNV
typedef GLXVideoCaptureDeviceNV *(APIENTRYP PFNXGLUXENUMERATEVIDEOCAPTUREDEVICESNVPROC) (Display *dpy, int screen, int *nelements);
#endif
#ifndef __GLUX__GLFCT_glXLockVideoCaptureDeviceNV
typedef void (APIENTRYP PFNXGLUXLOCKVIDEOCAPTUREDEVICENVPROC) (Display *dpy, GLXVideoCaptureDeviceNV device);
#endif
#ifndef __GLUX__GLFCT_glXQueryVideoCaptureDeviceNV
typedef int (APIENTRYP PFNXGLUXQUERYVIDEOCAPTUREDEVICENVPROC) (Display *dpy, GLXVideoCaptureDeviceNV device, int attribute, int *value);
#endif
#ifndef __GLUX__GLFCT_glXReleaseVideoCaptureDeviceNV
typedef void (APIENTRYP PFNXGLUXRELEASEVIDEOCAPTUREDEVICENVPROC) (Display *dpy, GLXVideoCaptureDeviceNV device);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glXBindVideoCaptureDeviceNV
extern PFNXGLUXBINDVIDEOCAPTUREDEVICENVPROC glXBindVideoCaptureDeviceNV;
#endif
#ifndef __GLUX__GLFCT_glXEnumerateVideoCaptureDevicesNV
extern PFNXGLUXENUMERATEVIDEOCAPTUREDEVICESNVPROC glXEnumerateVideoCaptureDevicesNV;
#endif
#ifndef __GLUX__GLFCT_glXLockVideoCaptureDeviceNV
extern PFNXGLUXLOCKVIDEOCAPTUREDEVICENVPROC glXLockVideoCaptureDeviceNV;
#endif
#ifndef __GLUX__GLFCT_glXQueryVideoCaptureDeviceNV
extern PFNXGLUXQUERYVIDEOCAPTUREDEVICENVPROC glXQueryVideoCaptureDeviceNV;
#endif
#ifndef __GLUX__GLFCT_glXReleaseVideoCaptureDeviceNV
extern PFNXGLUXRELEASEVIDEOCAPTUREDEVICENVPROC glXReleaseVideoCaptureDeviceNV;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
