
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GLX_NV_video_out__
#define __GLUX_GLX_NV_video_out__

GLUX_NEW_PLUGIN(GLX_NV_video_out)
// --------------------------------------------------------
#if !(defined WIN32 || defined(_WIN64) || defined __APPLE__ || defined EMSCRIPTEN)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef GLX_VIDEO_OUT_COLOR_NV
#    define GLX_VIDEO_OUT_COLOR_NV 0x20C3
#  endif
#  ifndef GLX_VIDEO_OUT_ALPHA_NV
#    define GLX_VIDEO_OUT_ALPHA_NV 0x20C4
#  endif
#  ifndef GLX_VIDEO_OUT_DEPTH_NV
#    define GLX_VIDEO_OUT_DEPTH_NV 0x20C5
#  endif
#  ifndef GLX_VIDEO_OUT_COLOR_AND_ALPHA_NV
#    define GLX_VIDEO_OUT_COLOR_AND_ALPHA_NV 0x20C6
#  endif
#  ifndef GLX_VIDEO_OUT_COLOR_AND_DEPTH_NV
#    define GLX_VIDEO_OUT_COLOR_AND_DEPTH_NV 0x20C7
#  endif
#  ifndef GLX_VIDEO_OUT_FRAME_NV
#    define GLX_VIDEO_OUT_FRAME_NV 0x20C8
#  endif
#  ifndef GLX_VIDEO_OUT_FIELD_1_NV
#    define GLX_VIDEO_OUT_FIELD_1_NV 0x20C9
#  endif
#  ifndef GLX_VIDEO_OUT_FIELD_2_NV
#    define GLX_VIDEO_OUT_FIELD_2_NV 0x20CA
#  endif
#  ifndef GLX_VIDEO_OUT_STACKED_FIELDS_1_2_NV
#    define GLX_VIDEO_OUT_STACKED_FIELDS_1_2_NV 0x20CB
#  endif
#  ifndef GLX_VIDEO_OUT_STACKED_FIELDS_2_1_NV
#    define GLX_VIDEO_OUT_STACKED_FIELDS_2_1_NV 0x20CC
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_glXGetVideoDeviceNV
typedef int (APIENTRYP PFNXGLUXGETVIDEODEVICENVPROC) (Display *dpy, int screen, int numVideoDevices, GLXVideoDeviceNV *pVideoDevice);
#endif
#ifndef __GLUX__GLFCT_glXReleaseVideoDeviceNV
typedef int (APIENTRYP PFNXGLUXRELEASEVIDEODEVICENVPROC) (Display *dpy, int screen, GLXVideoDeviceNV VideoDevice);
#endif
#ifndef __GLUX__GLFCT_glXBindVideoImageNV
typedef int (APIENTRYP PFNXGLUXBINDVIDEOIMAGENVPROC) (Display *dpy, GLXVideoDeviceNV VideoDevice, GLXPbuffer pbuf, int iVideoBuffer);
#endif
#ifndef __GLUX__GLFCT_glXReleaseVideoImageNV
typedef int (APIENTRYP PFNXGLUXRELEASEVIDEOIMAGENVPROC) (Display *dpy, GLXPbuffer pbuf);
#endif
#ifndef __GLUX__GLFCT_glXSendPbufferToVideoNV
typedef int (APIENTRYP PFNXGLUXSENDPBUFFERTOVIDEONVPROC) (Display *dpy, GLXPbuffer pbuf, int iBufferType, unsigned long *pulCounterPbuffer, GLboolean bBlock);
#endif
#ifndef __GLUX__GLFCT_glXGetVideoInfoNV
typedef int (APIENTRYP PFNXGLUXGETVIDEOINFONVPROC) (Display *dpy, int screen, GLXVideoDeviceNV VideoDevice, unsigned long *pulCounterOutputPbuffer, unsigned long *pulCounterOutputVideo);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_glXGetVideoDeviceNV
extern PFNXGLUXGETVIDEODEVICENVPROC glXGetVideoDeviceNV;
#endif
#ifndef __GLUX__GLFCT_glXReleaseVideoDeviceNV
extern PFNXGLUXRELEASEVIDEODEVICENVPROC glXReleaseVideoDeviceNV;
#endif
#ifndef __GLUX__GLFCT_glXBindVideoImageNV
extern PFNXGLUXBINDVIDEOIMAGENVPROC glXBindVideoImageNV;
#endif
#ifndef __GLUX__GLFCT_glXReleaseVideoImageNV
extern PFNXGLUXRELEASEVIDEOIMAGENVPROC glXReleaseVideoImageNV;
#endif
#ifndef __GLUX__GLFCT_glXSendPbufferToVideoNV
extern PFNXGLUXSENDPBUFFERTOVIDEONVPROC glXSendPbufferToVideoNV;
#endif
#ifndef __GLUX__GLFCT_glXGetVideoInfoNV
extern PFNXGLUXGETVIDEOINFONVPROC glXGetVideoInfoNV;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
