
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:02 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_GLX_SGIX_dmbuffer__
#define __GLUX_GLX_SGIX_dmbuffer__

GLUX_NEW_PLUGIN(GLX_SGIX_dmbuffer)
// --------------------------------------------------------
#if !(defined WIN32 || defined(_WIN64) || defined __APPLE__ || defined EMSCRIPTEN)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#ifdef _DM_BUFFER_H_
#  ifndef GLX_DIGITAL_MEDIA_PBUFFER_SGIX
#    define GLX_DIGITAL_MEDIA_PBUFFER_SGIX 0x8024
#  endif
#endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifdef _DM_BUFFER_H_
#ifdef _DM_BUFFER_H_
#ifndef __GLUX__GLFCT_glXAssociateDMPbufferSGIX
typedef Bool (APIENTRYP PFNXGLUXASSOCIATEDMPBUFFERSGIXPROC) (Display *dpy, GLXPbufferSGIX pbuffer, DMparams *params, DMbuffer dmbuffer);
#endif
#endif
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifdef _DM_BUFFER_H_
#ifdef _DM_BUFFER_H_
#ifndef __GLUX__GLFCT_glXAssociateDMPbufferSGIX
extern PFNXGLUXASSOCIATEDMPBUFFERSGIXPROC glXAssociateDMPbufferSGIX;
#endif
#endif
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
