
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:03 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_WGL_NV_present_video__
#define __GLUX_WGL_NV_present_video__

GLUX_NEW_PLUGIN(WGL_NV_present_video)
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef WGL_NUM_VIDEO_SLOTS_NV
#    define WGL_NUM_VIDEO_SLOTS_NV 0x20F0
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_wglEnumerateVideoDevicesNV
typedef int (APIENTRYP PFNWGLUXENUMERATEVIDEODEVICESNVPROC) (HDC hDC, HVIDEOOUTPUTDEVICENV *phDeviceList);
#endif
#ifndef __GLUX__GLFCT_wglBindVideoDeviceNV
typedef BOOL (APIENTRYP PFNWGLUXBINDVIDEODEVICENVPROC) (HDC hDC, unsigned int uVideoSlot, HVIDEOOUTPUTDEVICENV hVideoDevice, const int *piAttribList);
#endif
#ifndef __GLUX__GLFCT_wglQueryCurrentContextNV
typedef BOOL (APIENTRYP PFNWGLUXQUERYCURRENTCONTEXTNVPROC) (int iAttribute, int *piValue);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_wglEnumerateVideoDevicesNV
extern PFNWGLUXENUMERATEVIDEODEVICESNVPROC wglEnumerateVideoDevicesNV;
#endif
#ifndef __GLUX__GLFCT_wglBindVideoDeviceNV
extern PFNWGLUXBINDVIDEODEVICENVPROC wglBindVideoDeviceNV;
#endif
#ifndef __GLUX__GLFCT_wglQueryCurrentContextNV
extern PFNWGLUXQUERYCURRENTCONTEXTNVPROC wglQueryCurrentContextNV;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
