
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_WGL_I3D_swap_frame_lock__
#define __GLUX_WGL_I3D_swap_frame_lock__

GLUX_NEW_PLUGIN(WGL_I3D_swap_frame_lock)
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_wglEnableFrameLockI3D
typedef BOOL (APIENTRYP PFNWGLUXENABLEFRAMELOCKI3DPROC) (void);
#endif
#ifndef __GLUX__GLFCT_wglDisableFrameLockI3D
typedef BOOL (APIENTRYP PFNWGLUXDISABLEFRAMELOCKI3DPROC) (void);
#endif
#ifndef __GLUX__GLFCT_wglIsEnabledFrameLockI3D
typedef BOOL (APIENTRYP PFNWGLUXISENABLEDFRAMELOCKI3DPROC) (BOOL *pFlag);
#endif
#ifndef __GLUX__GLFCT_wglQueryFrameLockMasterI3D
typedef BOOL (APIENTRYP PFNWGLUXQUERYFRAMELOCKMASTERI3DPROC) (BOOL *pFlag);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_wglEnableFrameLockI3D
extern PFNWGLUXENABLEFRAMELOCKI3DPROC wglEnableFrameLockI3D;
#endif
#ifndef __GLUX__GLFCT_wglDisableFrameLockI3D
extern PFNWGLUXDISABLEFRAMELOCKI3DPROC wglDisableFrameLockI3D;
#endif
#ifndef __GLUX__GLFCT_wglIsEnabledFrameLockI3D
extern PFNWGLUXISENABLEDFRAMELOCKI3DPROC wglIsEnabledFrameLockI3D;
#endif
#ifndef __GLUX__GLFCT_wglQueryFrameLockMasterI3D
extern PFNWGLUXQUERYFRAMELOCKMASTERI3DPROC wglQueryFrameLockMasterI3D;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
