
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_WGL_I3D_swap_frame_usage__
#define __GLUX_WGL_I3D_swap_frame_usage__

GLUX_NEW_PLUGIN(WGL_I3D_swap_frame_usage)
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_wglGetFrameUsageI3D
typedef BOOL (APIENTRYP PFNWGLUXGETFRAMEUSAGEI3DPROC) (float *pUsage);
#endif
#ifndef __GLUX__GLFCT_wglBeginFrameTrackingI3D
typedef BOOL (APIENTRYP PFNWGLUXBEGINFRAMETRACKINGI3DPROC) (void);
#endif
#ifndef __GLUX__GLFCT_wglEndFrameTrackingI3D
typedef BOOL (APIENTRYP PFNWGLUXENDFRAMETRACKINGI3DPROC) (void);
#endif
#ifndef __GLUX__GLFCT_wglQueryFrameTrackingI3D
typedef BOOL (APIENTRYP PFNWGLUXQUERYFRAMETRACKINGI3DPROC) (DWORD *pFrameCount, DWORD *pMissedFrames, float *pLastMissedUsage);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_wglGetFrameUsageI3D
extern PFNWGLUXGETFRAMEUSAGEI3DPROC wglGetFrameUsageI3D;
#endif
#ifndef __GLUX__GLFCT_wglBeginFrameTrackingI3D
extern PFNWGLUXBEGINFRAMETRACKINGI3DPROC wglBeginFrameTrackingI3D;
#endif
#ifndef __GLUX__GLFCT_wglEndFrameTrackingI3D
extern PFNWGLUXENDFRAMETRACKINGI3DPROC wglEndFrameTrackingI3D;
#endif
#ifndef __GLUX__GLFCT_wglQueryFrameTrackingI3D
extern PFNWGLUXQUERYFRAMETRACKINGI3DPROC wglQueryFrameTrackingI3D;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
