
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_WGL_NV_render_depth_texture__
#define __GLUX_WGL_NV_render_depth_texture__

GLUX_NEW_PLUGIN(WGL_NV_render_depth_texture)
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef WGL_BIND_TO_TEXTURE_DEPTH_NV
#    define WGL_BIND_TO_TEXTURE_DEPTH_NV 0x20A3
#  endif
#  ifndef WGL_BIND_TO_TEXTURE_RECTANGLE_DEPTH_NV
#    define WGL_BIND_TO_TEXTURE_RECTANGLE_DEPTH_NV 0x20A4
#  endif
#  ifndef WGL_DEPTH_TEXTURE_FORMAT_NV
#    define WGL_DEPTH_TEXTURE_FORMAT_NV 0x20A5
#  endif
#  ifndef WGL_TEXTURE_DEPTH_COMPONENT_NV
#    define WGL_TEXTURE_DEPTH_COMPONENT_NV 0x20A6
#  endif
#  ifndef WGL_DEPTH_COMPONENT_NV
#    define WGL_DEPTH_COMPONENT_NV 0x20A7
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
