
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_WGL_ARB_create_context__
#define __GLUX_WGL_ARB_create_context__

GLUX_NEW_PLUGIN(WGL_ARB_create_context)
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef WGL_CONTEXT_DEBUG_BIT_ARB
#    define WGL_CONTEXT_DEBUG_BIT_ARB 0x00000001
#  endif
#  ifndef WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB
#    define WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB 0x00000002
#  endif
#  ifndef WGL_CONTEXT_MAJOR_VERSION_ARB
#    define WGL_CONTEXT_MAJOR_VERSION_ARB 0x2091
#  endif
#  ifndef WGL_CONTEXT_MINOR_VERSION_ARB
#    define WGL_CONTEXT_MINOR_VERSION_ARB 0x2092
#  endif
#  ifndef WGL_CONTEXT_LAYER_PLANE_ARB
#    define WGL_CONTEXT_LAYER_PLANE_ARB 0x2093
#  endif
#  ifndef WGL_CONTEXT_FLAGS_ARB
#    define WGL_CONTEXT_FLAGS_ARB 0x2094
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_wglCreateContextAttribsARB
typedef HGLRC (APIENTRYP PFNWGLUXCREATECONTEXTATTRIBSARBPROC) (HDC hDC, HGLRC hShareContext, const int *attribList);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_wglCreateContextAttribsARB
extern PFNWGLUXCREATECONTEXTATTRIBSARBPROC wglCreateContextAttribsARB;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
