
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:03 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_WGL_OML_sync_control__
#define __GLUX_WGL_OML_sync_control__

GLUX_NEW_PLUGIN(WGL_OML_sync_control)
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_wglGetSyncValuesOML
typedef BOOL (APIENTRYP PFNWGLUXGETSYNCVALUESOMLPROC) (HDC hdc, INT64 *ust, INT64 *msc, INT64 *sbc);
#endif
#ifndef __GLUX__GLFCT_wglGetMscRateOML
typedef BOOL (APIENTRYP PFNWGLUXGETMSCRATEOMLPROC) (HDC hdc, INT32 *numerator, INT32 *denominator);
#endif
#ifndef __GLUX__GLFCT_wglSwapBuffersMscOML
typedef INT64 (APIENTRYP PFNWGLUXSWAPBUFFERSMSCOMLPROC) (HDC hdc, INT64 target_msc, INT64 divisor, INT64 remainder);
#endif
#ifndef __GLUX__GLFCT_wglSwapLayerBuffersMscOML
typedef INT64 (APIENTRYP PFNWGLUXSWAPLAYERBUFFERSMSCOMLPROC) (HDC hdc, int fuPlanes, INT64 target_msc, INT64 divisor, INT64 remainder);
#endif
#ifndef __GLUX__GLFCT_wglWaitForMscOML
typedef BOOL (APIENTRYP PFNWGLUXWAITFORMSCOMLPROC) (HDC hdc, INT64 target_msc, INT64 divisor, INT64 remainder, INT64 *ust, INT64 *msc, INT64 *sbc);
#endif
#ifndef __GLUX__GLFCT_wglWaitForSbcOML
typedef BOOL (APIENTRYP PFNWGLUXWAITFORSBCOMLPROC) (HDC hdc, INT64 target_sbc, INT64 *ust, INT64 *msc, INT64 *sbc);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_wglGetSyncValuesOML
extern PFNWGLUXGETSYNCVALUESOMLPROC wglGetSyncValuesOML;
#endif
#ifndef __GLUX__GLFCT_wglGetMscRateOML
extern PFNWGLUXGETMSCRATEOMLPROC wglGetMscRateOML;
#endif
#ifndef __GLUX__GLFCT_wglSwapBuffersMscOML
extern PFNWGLUXSWAPBUFFERSMSCOMLPROC wglSwapBuffersMscOML;
#endif
#ifndef __GLUX__GLFCT_wglSwapLayerBuffersMscOML
extern PFNWGLUXSWAPLAYERBUFFERSMSCOMLPROC wglSwapLayerBuffersMscOML;
#endif
#ifndef __GLUX__GLFCT_wglWaitForMscOML
extern PFNWGLUXWAITFORMSCOMLPROC wglWaitForMscOML;
#endif
#ifndef __GLUX__GLFCT_wglWaitForSbcOML
extern PFNWGLUXWAITFORSBCOMLPROC wglWaitForSbcOML;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
