
// --------------------------------------------------------
// Generated by glux perl script (Fri Feb  7 10:09:04 2020)
// 
// Sylvain Lefebvre - 2002-2014 - Sylvain.Lefebvre@inria.fr
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
#  include <windows.h>
#endif
#ifdef __APPLE__
#  define GL_GLEXT_LEGACY
#endif

#ifndef GL_ARB_multitexture // hack due to MESA headers including GL_ARB_multitexture
#define GL_ARB_multitexture
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#else
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/gl.h>
#endif
#undef  GL_ARB_multitexture
#endif

#undef  GL_GLEXT_PROTOTYPES
#if defined(_WIN32) || defined(_WIN64)
#  include "glux_glext.h"
#  include "glux_wglext.h"
#else
#ifdef __APPLE__
//#  include "glux_glext_apple.h"
#  include "glux_glext.h"
#else
#ifdef EMSCRIPTEN
#  include "glux_glext.h"
#else
#  include <GL/glx.h>
#  include "glux_glext.h"
#  include "glux_glxext.h"
#endif
#endif
#endif
#include "gluxLoader.h"
#include "gluxPlugin.h"
// --------------------------------------------------------
//         Plugin creation
// --------------------------------------------------------

#ifndef __GLUX_WGL_I3D_digital_video_control__
#define __GLUX_WGL_I3D_digital_video_control__

GLUX_NEW_PLUGIN(WGL_I3D_digital_video_control)
// --------------------------------------------------------
#if defined(_WIN32) || defined(_WIN64)
// --------------------------------------------------------
//           Extension defines
// --------------------------------------------------------
#  ifndef WGL_DIGITAL_VIDEO_CURSOR_ALPHA_FRAMEBUFFER_I3D
#    define WGL_DIGITAL_VIDEO_CURSOR_ALPHA_FRAMEBUFFER_I3D 0x2050
#  endif
#  ifndef WGL_DIGITAL_VIDEO_CURSOR_ALPHA_VALUE_I3D
#    define WGL_DIGITAL_VIDEO_CURSOR_ALPHA_VALUE_I3D 0x2051
#  endif
#  ifndef WGL_DIGITAL_VIDEO_CURSOR_INCLUDED_I3D
#    define WGL_DIGITAL_VIDEO_CURSOR_INCLUDED_I3D 0x2052
#  endif
#  ifndef WGL_DIGITAL_VIDEO_GAMMA_CORRECTED_I3D
#    define WGL_DIGITAL_VIDEO_GAMMA_CORRECTED_I3D 0x2053
#  endif
// --------------------------------------------------------
//           Extension gl function typedefs
// --------------------------------------------------------
#ifndef __GLUX__GLFCT_wglGetDigitalVideoParametersI3D
typedef BOOL (APIENTRYP PFNWGLUXGETDIGITALVIDEOPARAMETERSI3DPROC) (HDC hDC, int iAttribute, int *piValue);
#endif
#ifndef __GLUX__GLFCT_wglSetDigitalVideoParametersI3D
typedef BOOL (APIENTRYP PFNWGLUXSETDIGITALVIDEOPARAMETERSI3DPROC) (HDC hDC, int iAttribute, const int *piValue);
#endif
// --------------------------------------------------------
//           Extension gl functions
// --------------------------------------------------------
namespace glux {
#ifndef __GLUX__GLFCT_wglGetDigitalVideoParametersI3D
extern PFNWGLUXGETDIGITALVIDEOPARAMETERSI3DPROC wglGetDigitalVideoParametersI3D;
#endif
#ifndef __GLUX__GLFCT_wglSetDigitalVideoParametersI3D
extern PFNWGLUXSETDIGITALVIDEOPARAMETERSI3DPROC wglSetDigitalVideoParametersI3D;
#endif
} // namespace glux
// --------------------------------------------------------
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
